package com.wsc.common.user;

import java.io.IOException;

import javax.inject.Provider;
import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import com.wsc.common.mail.MailService;
import com.wsc.common.security.SessionComponent;
import com.wsc.framework.base.BaseController;
import com.wsc.framework.base.BaseService;
import com.wsc.framework.model.ParamsMap;
import com.wsc.framework.utils.MailUtils;

@Controller
@RequestMapping("/common/password")
public class PasswordController extends BaseController {
	@Autowired 
	private PasswordService passwordService;
	
	@Autowired 
	private MailService mailService;
	
	@Autowired 
	private Provider<SessionComponent> sessionProvider;

	@Override
	protected BaseService getService() {
		return this.passwordService;
	}
	@Override
	protected SessionComponent getSessionComponent() {
		return this.sessionProvider.get();
	}
	
	@RequestMapping(value = "/password.do")
	public String open(HttpServletRequest request, Model model) {
		ParamsMap params = getParams(request);
		model.addAttribute("gsUserId", params.get("gsUserId"));
		return super.open(request, model);
	}
	
	@RequestMapping(value = "/userpassword.do")
	public String userOpen(HttpServletRequest request, Model model) {
		ParamsMap params = getParams(request);
		model.addAttribute("gsUserId", params.get("gsUserId"));
		return super.open(request, model, "userPassword");
	}
	
	@RequestMapping(value = "/save.json")
	public String save(HttpServletRequest request, Model model) {
		// 파라메터를 가져온다.
    	ParamsMap params = getParams(request, true);
    	
    	Object result = passwordService.update("updateUserPw", params);
	    
	    // 모델에 객체를 추가한다.
	    addObject(model, result);
	    
	    // 뷰이름을 반환한다.
	    return "jsonView";
	}
	//Change Password 화면에서 사용
	@RequestMapping(value = "/userPwChk.json")
	public String chkPw(HttpServletRequest request, Model model) {
		// 파라메터를 가져온다.
    	ParamsMap params = getParams(request, true);
    	
    	Object result = passwordService.select("chkUserPw", params);
	    
    	// 인증 실패 횟수 제한
    	if (result == null) {
			//로그인 실패시 카운트 증가
    		passwordService.update("updateLoginNG",params);
    	} else{
			//로그인 성공시 카운트 증가
    		passwordService.update("updateLoginOK",params);
    	}
    	
	    // 모델에 객체를 추가한다.
	    addObject(model, result);
	    
	    // 뷰이름을 반환한다.
	    return "jsonView";
	}
	//Log IN 화면에서 사용 (chkPw에서  마스터키기능 추가로 인해 추가시킴)
	@RequestMapping(value = "/userPwChk2.json")
	public String userPwChk2(HttpServletRequest request, Model model) {
		// 파라메터를 가져온다.
    	ParamsMap params = getParams(request, true);
    	
    	Object result = passwordService.select("chkUserPw2", params);
	    
    	// 인증 실패 횟수 제한
    	if (result == null) {
			//로그인 실패시 카운트 증가
    		passwordService.update("updateLoginNG",params);
    	} else{
			//로그인 성공시 카운트 증가
    		passwordService.update("updateLoginOK",params);
    	}
	    // 모델에 객체를 추가한다.
	    addObject(model, result);
	    
	    // 뷰이름을 반환한다.
	    return "jsonView";
	}
	
	@RequestMapping(value = "/saveUserPw.json")
	public String saveUserPw(HttpServletRequest request, Model model) {
		// 파라메터를 가져온다.
    	ParamsMap params = getParams(request, true);
    	
    	Object result = passwordService.update("updateUserPw-user", params);
	    
	    // 모델에 객체를 추가한다.
	    addObject(model, result);
	    
	    // 뷰이름을 반환한다.
	    return "jsonView";
	}
	
	@RequestMapping(value = "/emailCheck.json")
	public String emailCheck(HttpServletRequest request, Model model) {
		// 파라메터를 가져온다.
    	ParamsMap params = getParams(request, true);
    	Object result = "";
    	try {
    		result = passwordService.select("emailCheck", params);
    		if(result != null) {
    			params.put("mail_to",params.get("email").toString());
    			String newPw_bk = result.toString();
    			String[] newPw = newPw_bk.split("=");
    			params.put(newPw[0].replace("{", ""),newPw[1].replace("}", ""));
    			params.put("bordText","Your password has been changed to <b>" + params.getString("newPw") + "</b><br><br>This message has been automatically generated by program.<br>Please do not reply to this message.");
    			result = passwordService.update("updateUserPw", params);
    			mailService.lstaMail(params);
    		}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    
	    // 모델에 객체를 추가한다.
	    addObject(model, result);
	    
	    // 뷰이름을 반환한다.
	    return "jsonView";
	}
	
	@RequestMapping(value = "/chkUserChar.json")
	public String chkUserChar(HttpServletRequest request, Model model) {
		// 파라메터를 가져온다.
    	ParamsMap params = getParams(request, true);
    	
    	Object result = passwordService.select("chkUserChar", params);
	    
	    // 모델에 객체를 추가한다.
	    addObject(model, result);
	    
	    // 뷰이름을 반환한다.
	    return "jsonView";
	}
	
	@RequestMapping(value = "/checkLoginSts.json")
	public String checkLoginSts(HttpServletRequest request, Model model) {
		// 파라메터를 가져온다.
    	ParamsMap params = getParams(request, true);
    	
    	Object result = passwordService.select("checkLoginSts", params);
	    
	    // 모델에 객체를 추가한다.
	    addObject(model, result);
	    
	    // 뷰이름을 반환한다.
	    return "jsonView";
	}
	
	@RequestMapping(value = "/RejectCheck.json")
	public String RejectCheck(HttpServletRequest request, Model model) {
		// 파라메터를 가져온다.
    	ParamsMap params = getParams(request, true);
    	
    	Object result = passwordService.update("RejectCheck", params);
	    
	    // 모델에 객체를 추가한다.
	    addObject(model, result);
	    
	    // 뷰이름을 반환한다.
	    return "jsonView";
	}
	
	@RequestMapping(value = "/RejectMail.json")
	public String RejectMail(HttpServletRequest request, Model model) {
		// 파라메터를 가져온다.
    	ParamsMap params = getParams(request, true);
    	
    	String id = params.get("userId").toString();
		String tokenNo = params.get("ftokenNo").toString();
		String rejectMail = params.get("Cmail").toString();
		String passTitle = params.get("passTitle").toString();
		String gpNo = params.get("gpNo").toString();
		String bolNo = params.get("bolNo").toString();
		String PassDate = params.get("PassDate").toString();
		String PassTime = params.get("PassTime").toString();
		String GateToUse = params.get("GateToUse").toString();
		String Reason = params.get("Reason").toString();
		
		System.out.println("****************************["+id+"]****************************");
		System.out.println("****************************["+tokenNo+"]****************************");
		
		String bordTitle2 = MailUtils.MailRejectTitle(passTitle);
		String bordText2 = MailUtils.MailRejectForm(passTitle,rejectMail,PassDate,PassTime,gpNo,GateToUse,bolNo,Reason);
		params.put("bordTitle2",  bordTitle2);
		params.put("bordText2", bordText2);
		model.addAttribute("bolNo", bolNo);
		
		try {
			mailService.rejectMail(params);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Object result = "";
	    // 모델에 객체를 추가한다.
	    addObject(model, result);
	    
	    // 뷰이름을 반환한다.
	    return "jsonView";
	}
	
}
