/* 2015-05-04 CREATE */

DROP TABLE SYS_EXCL_FORM CASCADE CONSTRAINTS;

CREATE TABLE SYS_EXCL_FORM
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  EXCL_GRUP  VARCHAR2(20 BYTE)                  NOT NULL,
  FORM_CODE  VARCHAR2(20 BYTE)                  NOT NULL,
  FORM_NAME  VARCHAR2(128 BYTE),
  FORM_DESC  VARCHAR2(256 BYTE),
  TITLE_NO   NUMBER(5)           DEFAULT 1      NOT NULL,
  START_NO   NUMBER(5)           DEFAULT 2      NOT NULL,
  PIVOT_YN   CHAR(1 BYTE)        DEFAULT 'N'    NOT NULL,
  USE_FLAG   CHAR(1 BYTE)        DEFAULT 'Y'    NOT NULL,
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY (SYS_ID, EXCL_GRUP, FORM_CODE)
);
COMMENT ON  TABLE SYS_EXCL_FORM            IS '엑셀맵핑 양식정보';
COMMENT ON COLUMN SYS_EXCL_FORM.SYS_ID     IS '시스템ID';
COMMENT ON COLUMN SYS_EXCL_FORM.EXCL_GRUP  IS '엑셀그룹';
COMMENT ON COLUMN SYS_EXCL_FORM.FORM_CODE  IS '엑셀양식코드';
COMMENT ON COLUMN SYS_EXCL_FORM.FORM_NAME  IS '엑셀양식명칭';
COMMENT ON COLUMN SYS_EXCL_FORM.FORM_DESC  IS '엑셀양식설명';
COMMENT ON COLUMN SYS_EXCL_FORM.TITLE_NO   IS '제목행번호';
COMMENT ON COLUMN SYS_EXCL_FORM.START_NO   IS '시작행번호';
COMMENT ON COLUMN SYS_EXCL_FORM.PIVOT_YN   IS '피벗여부';
COMMENT ON COLUMN SYS_EXCL_FORM.USE_FLAG   IS '사용유무';
COMMENT ON COLUMN SYS_EXCL_FORM.REGI_ID    IS '등록자';
COMMENT ON COLUMN SYS_EXCL_FORM.REGI_DATE  IS '등록일자';
COMMENT ON COLUMN SYS_EXCL_FORM.CHNG_ID    IS '수정자';
COMMENT ON COLUMN SYS_EXCL_FORM.CHNG_DATE  IS '수정일자';

DROP TABLE SYS_EXCL_ITEM CASCADE CONSTRAINTS;

CREATE TABLE SYS_EXCL_ITEM
(
  SYS_ID     VARCHAR2(20  BYTE)                 NOT NULL,
  EXCL_GRUP  VARCHAR2(20  BYTE)                 NOT NULL,
  FORM_CODE  VARCHAR2(20  BYTE)                 NOT NULL,
  ITEM_CODE  VARCHAR2(20  BYTE)                 NOT NULL,
  ITEM_NAME  VARCHAR2(128 BYTE),
  ITEM_TYPE  VARCHAR2(20  BYTE),
  ITEM_DESC  VARCHAR2(256 BYTE),
  ITEM_DEF   VARCHAR2(256 BYTE),
  ITEM_SEQ   NUMBER(5),
  EXCL_CODE  VARCHAR2(20  BYTE),
  USE_FLAG   CHAR(1 BYTE)         DEFAULT 'Y'   NOT NULL,
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY (SYS_ID, EXCL_GRUP, FORM_CODE, ITEM_CODE)
);

COMMENT ON  TABLE SYS_EXCL_ITEM            IS '엑셀맵핑 칼럼정보';
COMMENT ON COLUMN SYS_EXCL_ITEM.SYS_ID     IS '시스템ID';
COMMENT ON COLUMN SYS_EXCL_ITEM.EXCL_GRUP  IS '엑셀그룹';
COMMENT ON COLUMN SYS_EXCL_ITEM.EXCL_CODE  IS '엑셀칼럼';
COMMENT ON COLUMN SYS_EXCL_ITEM.FORM_CODE  IS '엑셀양식코드';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_CODE  IS '맵핑칼럼번호';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_NAME  IS '맵핑칼럼제목';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_TYPE  IS '맵핑칼럼타입';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_DESC  IS '맵핑칼럼설명';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_DEF   IS '맵핑칼럼초기값';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_SEQ   IS '맵핑칼럼순번';
COMMENT ON COLUMN SYS_EXCL_ITEM.USE_FLAG   IS '사용유무';
COMMENT ON COLUMN SYS_EXCL_ITEM.REGI_ID    IS '등록자';
COMMENT ON COLUMN SYS_EXCL_ITEM.REGI_DATE  IS '등록일자';
COMMENT ON COLUMN SYS_EXCL_ITEM.CHNG_ID    IS '수정자';
COMMENT ON COLUMN SYS_EXCL_ITEM.CHNG_DATE  IS '수정일자';
