-- 2014-09-20 추가
ALTER TABLE SYS_BORD ADD (BORD_PNO VARCHAR2(30 BYTE)       NULL);
COMMENT ON COLUMN SYS_BORD.BORD_PNO IS '게시물 상위번호';

-- 2014-10-01 수정
ALTER TABLE SYS_FILE MODIFY(FILE_TYPE VARCHAR2(128 BYTE));

-- 2015-05-20 추가
ALTER TABLE SYS_BORD ADD (OPEN_TYPE VARCHAR2(20 BYTE)       NULL);
COMMENT ON COLUMN SYS_BORD.OPEN_TYPE IS '팝업 오픈타입';

