
-- 2014.07.30  create
-- 2014.08.02  create
-- 2014.08.04  create
-- 2014.08.05  create

TRUNCATE TABLE SYS_PROG;
TRUNCATE TABLE SYS_GPGM;
TRUNCATE TABLE SYS_MENU;

--INSERT INTO SYS_GRUP (SYS_ID, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, GROUP_ID, GROUP_NAME) VALUES ('WSC', 'system', SYSDATE, 'system', SYSDATE, 'ANONYMOUS', '������ ����� �׷�');

INSERT INTO SYS_CODE (SYS_ID, CODE_GRUP, CODE_CD, SORT_SEQ, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, CODE_NAME) VALUES 
('WSC',  '0',  '0', 1, 'Y', 'system', SYSDATE, 'system', SYSDATE, '�ڵ�׷�');
INSERT INTO SYS_CODE (SYS_ID, CODE_GRUP, CODE_CD, SORT_SEQ, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, CODE_NAME) VALUES 
('WSC',  '0',  'BORD_GRUP', 1, 'Y', 'system', SYSDATE, 'system', SYSDATE, '�Խ�������');
INSERT INTO SYS_CODE (SYS_ID, CODE_GRUP, CODE_CD, SORT_SEQ, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, CODE_NAME) VALUES 
('WSC', 'BORD_GRUP', 'B01', 1, 'Y', 'system', SYSDATE, 'system', SYSDATE, '��������');
INSERT INTO SYS_CODE (SYS_ID, CODE_GRUP, CODE_CD, SORT_SEQ, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, CODE_NAME) VALUES 
('WSC', 'BORD_GRUP', 'B02', 2, 'Y', 'system', SYSDATE, 'system', SYSDATE, '�Խ���'  );
INSERT INTO SYS_CODE (SYS_ID, CODE_GRUP, CODE_CD, SORT_SEQ, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, CODE_NAME) VALUES 
('WSC', 'BORD_GRUP', 'B03', 3, 'Y', 'system', SYSDATE, 'system', SYSDATE, '�ڷ��'  );
INSERT INTO SYS_CODE (SYS_ID, CODE_GRUP, CODE_CD, SORT_SEQ, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, CODE_NAME) VALUES 
('WSC', 'BORD_GRUP', 'B04', 4, 'Y', 'system', SYSDATE, 'system', SYSDATE, 'Q&A'     );
INSERT INTO SYS_CODE (SYS_ID, CODE_GRUP, CODE_CD, SORT_SEQ, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, CODE_NAME) VALUES 
('WSC', 'BORD_GRUP', 'B05', 5, 'Y', 'system', SYSDATE, 'system', SYSDATE, '��'    );
INSERT INTO SYS_CODE (SYS_ID, CODE_GRUP, CODE_CD, SORT_SEQ, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, CODE_NAME) VALUES 
('WSC', 'BORD_GRUP', 'B06', 6, 'Y', 'system', SYSDATE, 'system', SYSDATE, '�˾�'    );

INSERT INTO SYS_USER (SYS_ID, USER_PWD, USER_TYPE, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, USER_ID, USER_NAME) VALUES ('WSC', '1111', 'A', 'Y', 'system', SYSDATE, 'system', SYSDATE, 'admin', '����' );
INSERT INTO SYS_USER (SYS_ID, USER_PWD, USER_TYPE, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, USER_ID, USER_NAME) VALUES ('WSC', '1111', 'C', 'Y', 'system', SYSDATE, 'system', SYSDATE, 'user1', '�����1');
INSERT INTO SYS_USER (SYS_ID, USER_PWD, USER_TYPE, USE_FLAG, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, USER_ID, USER_NAME) VALUES ('WSC', '1111', 'C', 'Y', 'system', SYSDATE, 'system', SYSDATE, 'user2', '�����2');

INSERT INTO SYS_GRUP (SYS_ID, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, GROUP_ID, GROUP_NAME) VALUES ('WSC', 'system', SYSDATE, 'system', SYSDATE, 'SYSTEM',    '�ý��� ��׷�');
INSERT INTO SYS_GRUP (SYS_ID, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, GROUP_ID, GROUP_NAME) VALUES ('WSC', 'system', SYSDATE, 'system', SYSDATE, 'USER01',    '����� �׷�01');
INSERT INTO SYS_GRUP (SYS_ID, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, GROUP_ID, GROUP_NAME) VALUES ('WSC', 'system', SYSDATE, 'system', SYSDATE, 'USER02',    '����� �׷�02');

INSERT INTO SYS_UGRP (SYS_ID, USER_ID, GROUP_ID, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE) VALUES ('WSC', 'admin', 'SYSTEM', 'system', SYSDATE, 'system', SYSDATE);
INSERT INTO SYS_UGRP (SYS_ID, USER_ID, GROUP_ID, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE) VALUES ('WSC', 'user1', 'USER01', 'system', SYSDATE, 'system', SYSDATE);
INSERT INTO SYS_UGRP (SYS_ID, USER_ID, GROUP_ID, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE) VALUES ('WSC', 'user2', 'USER02', 'system', SYSDATE, 'system', SYSDATE);

INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/index.do'                   , 'WSC ����');
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/login.do'                   , 'WSC �α���');
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/logout.do'                  , 'WSC �α׾ƿ�');
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/common/code/code.do'        , '�ڵ��'  );
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/common/user/user.do'        , '����ڰ�');
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/common/user/group.do'       , '�׷��'  );
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/common/user/menu.do'        , '�޴���'  );
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/common/user/program.do'     , 'ȭ���'  );    
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/common/user/usergroup.do'   , '����ڱ׷��');
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/common/user/userprogram.do' , '�����ȭ���');
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/common/user/groupprogram.do', '�׷�ȭ���'  );
INSERT INTO SYS_PROG (SYS_ID, USE_FLAG, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, PROG_ID, PROG_NAME) VALUES ('WSC', 'Y', '1', 'system', SYSDATE, 'system', SYSDATE, '/common/board/board.do'      , '�Խ��ǰ�'  );

INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '00000', '10000', 1, 'N',  1, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '#',                           '����1'     );   
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '00000', '20000', 1, 'N',  2, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '#',                           '����2'     ); 
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '00000', '30000', 1, 'N',  3, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '#',                           '����3'     ); 
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '00000', '40000', 1, 'N',  4, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '#',                           '����4'     ); 
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '00000', '50000', 1, 'N',  5, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '#',                           '����5'     ); 
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '00000', '60000', 1, 'N',  6, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '#',                           '����6'     ); 
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '00000', '70000', 1, 'N',  7, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '#',                           '��ü����'  );  
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '00000', '80000', 1, 'N',  8, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '#',                           '��ȣȸ'    );  
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '00000', '90000', 1, 'N',  9, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '#',                           '�ý��۰�'); 
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '90000', '91000', 2, 'N', 11, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '/common/code/code.do',        '�ڵ��');
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '90000', '92000', 2, 'N', 12, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '/common/user/user.do',        '����ڰ�'); 
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '90000', '93000', 2, 'N', 13, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '/common/user/group.do',       '�׷��');  
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '90000', '94000', 2, 'N', 14, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '/common/user/menu.do',        '�޴���');  
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '90000', '95000', 2, 'N', 15, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '/common/user/program.do',     'ȭ���');  
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '90000', '96000', 2, 'N', 16, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '/common/user/usergroup.do',   '����ڱ׷��');  
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '90000', '97000', 2, 'N', 17, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '/common/user/userprogram.do', '�����ȭ���');  
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '90000', '98000', 2, 'N', 18, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '/common/user/groupprogram.do','�׷�ȭ���');  
INSERT INTO SYS_MENU (SYS_ID, PARENT_KEY, MENU_KEY, MENU_LEVEL, CHILD_YN, MENU_SEQ, USE_FLAG, ENABLE_YN, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, MENU_URL, MENU_DESC) VALUES ('WSC', '90000', '99000', 2, 'N', 19, 'Y', 'Y', 'system', SYSDATE, 'system', SYSDATE, '/common/board/board.do',      '�Խ��ǰ�');

INSERT 
  INTO SYS_GPGM 
      (SYS_ID, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, GROUP_ID, PROG_ID)
SELECT SYS_ID, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, 'SYSTEM', PROG_ID 
  FROM SYS_PROG A
 WHERE NOT EXISTS (SELECT 1 FROM SYS_GPGM WHERE GROUP_ID = 'SYSTEM' AND PROG_ID = A.PROG_ID);

INSERT 
  INTO SYS_GPGM 
      (SYS_ID, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, GROUP_ID, PROG_ID)
SELECT SYS_ID, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, 'USER01', PROG_ID 
  FROM SYS_PROG A
 WHERE NOT EXISTS (SELECT 1 FROM SYS_GPGM WHERE GROUP_ID = 'USER01' AND PROG_ID = A.PROG_ID)
   AND A.PROG_ID NOT LIKE '/common/%';

INSERT 
  INTO SYS_GPGM 
      (SYS_ID, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, GROUP_ID, PROG_ID)
SELECT SYS_ID, TRAN_A, REGI_ID, REGI_DATE, CHNG_ID, CHNG_DATE, 'USER02', PROG_ID 
  FROM SYS_PROG A
 WHERE NOT EXISTS (SELECT 1 FROM SYS_GPGM WHERE GROUP_ID = 'USER02' AND PROG_ID = A.PROG_ID)
   AND A.PROG_ID NOT LIKE '/common/%';
