CREATE TABLE SYS_BORD
(
  SYS_ID      VARCHAR2(20 BYTE)                 NOT NULL,
  BORD_GRUP   VARCHAR2(20 BYTE)                 NOT NULL,
  BORD_NO     VARCHAR2(30 BYTE)                 NOT NULL,
  BORD_TITLE  VARCHAR2(128 BYTE),
  BORD_TEXT   VARCHAR2(4000 BYTE),
  BORD_TYPE   VARCHAR2(20 BYTE),
  BORD_BGN    VARCHAR2(10 BYTE),
  BORD_END    VARCHAR2(10 BYTE),
  BORD_PNO    VARCHAR2(30 BYTE),
  BORD_SEQ    NUMBER(10)           DEFAULT 0    NOT NULL,
  READ_CNT    NUMBER(7)            DEFAULT 0    NOT NULL,
  USE_FLAG    CHAR(1 BYTE),
  REGI_ID     VARCHAR2(20 BYTE),
  REGI_DATE   DATE,
  CHNG_ID     VARCHAR2(20 BYTE),
  CHNG_DATE   DATE,
  PRIMARY KEY (SYS_ID, BORD_GRUP, BORD_NO)
);




COMMENT ON TABLE SYS_BORD IS '게시판';
COMMENT ON COLUMN SYS_BORD.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD.BORD_GRUP IS '게시판 종류';
COMMENT ON COLUMN SYS_BORD.BORD_NO IS '게시물 번호';
COMMENT ON COLUMN SYS_BORD.BORD_PNO IS '게시물 상위번호';
COMMENT ON COLUMN SYS_BORD.BORD_BGN IS '게시 시작일';
COMMENT ON COLUMN SYS_BORD.BORD_END IS '게시 종료일';
COMMENT ON COLUMN SYS_BORD.BORD_TITLE IS '게시물 제목';
COMMENT ON COLUMN SYS_BORD.BORD_TEXT IS '게시물 내용';
COMMENT ON COLUMN SYS_BORD.BORD_TYPE IS '게시타입';
COMMENT ON COLUMN SYS_BORD.BORD_SEQ IS '조회순서';
COMMENT ON COLUMN SYS_BORD.READ_CNT IS '조회수';
COMMENT ON COLUMN SYS_BORD.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_BORD.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD.CHNG_DATE IS '수정일자';

  
CREATE TABLE SYS_BORD_TGT
(
  SYS_ID       VARCHAR2(20 BYTE)                NOT NULL,
  BORD_GRUP    VARCHAR2(20 BYTE)                NOT NULL,
  BORD_NO      VARCHAR2(30 BYTE)                NOT NULL,
  TGT_USER_ID  VARCHAR2(20 BYTE)                NOT NULL,
  VNDR_CODE    VARCHAR2(20 BYTE),
  VNDR_NAME    VARCHAR2(64 BYTE),
  READ_DATE    DATE,
  SAVE_IDX     CHAR(1 BYTE),
  USE_FLAG     CHAR(1 BYTE),
  REGI_ID      VARCHAR2(20 BYTE),
  REGI_DATE    DATE,
  CHNG_ID      VARCHAR2(20 BYTE),
  CHNG_DATE    DATE,
  PRIMARY KEY (SYS_ID, BORD_GRUP, BORD_NO, TGT_USER_ID)
);


COMMENT ON TABLE SYS_BORD_TGT IS '게시판-게시대상';
COMMENT ON COLUMN SYS_BORD_TGT.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD_TGT.BORD_GRUP IS '게시판 종류';
COMMENT ON COLUMN SYS_BORD_TGT.BORD_NO IS '게시물 번호';
COMMENT ON COLUMN SYS_BORD_TGT.TGT_USER_ID IS '게시대상 ID';
COMMENT ON COLUMN SYS_BORD_TGT.VNDR_CODE IS '업체코드';
COMMENT ON COLUMN SYS_BORD_TGT.VNDR_NAME IS '업체명칭';
COMMENT ON COLUMN SYS_BORD_TGT.READ_DATE IS '확인일시';
COMMENT ON COLUMN SYS_BORD_TGT.SAVE_IDX IS '보관여부';
COMMENT ON COLUMN SYS_BORD_TGT.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_BORD_TGT.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD_TGT.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD_TGT.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD_TGT.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_BORD_ADDR
(
  SYS_ID         VARCHAR2(20 BYTE)              NOT NULL,
  BORD_GRUP      VARCHAR2(20 BYTE)              NOT NULL,
  USER_ID        VARCHAR2(20 BYTE)              NOT NULL,
  TGT_USER_ID    VARCHAR2(20 BYTE)              NOT NULL,
  TGT_USER_NAME  VARCHAR2(64 BYTE),
  TGT_VNDR_CODE  VARCHAR2(20 BYTE),
  TGT_VNDR_NAME  VARCHAR2(64 BYTE),
  TGT_USER_RMK   VARCHAR2(128 BYTE),
  REGI_ID        VARCHAR2(20 BYTE),
  REGI_DATE      DATE,
  CHNG_ID        VARCHAR2(20 BYTE),
  CHNG_DATE      DATE,
  PRIMARY KEY (SYS_ID, BORD_GRUP, USER_ID, TGT_USER_ID)
);

COMMENT ON TABLE SYS_BORD_ADDR IS '게시판-주소록';
COMMENT ON COLUMN SYS_BORD_ADDR.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD_ADDR.BORD_GRUP IS '게시판 종류';
COMMENT ON COLUMN SYS_BORD_ADDR.USER_ID IS '사용자 ID';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_USER_ID IS '수신자 ID';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_USER_NAME IS '수신자명';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_VNDR_CODE IS '업체코드';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_VNDR_NAME IS '업체명칭';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_USER_RMK IS '비고';
COMMENT ON COLUMN SYS_BORD_ADDR.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD_ADDR.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD_ADDR.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD_ADDR.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_BORD_GRUP
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  BORD_GRUP     VARCHAR2(20 BYTE)               NOT NULL,
  USER_ID       VARCHAR2(20 BYTE)               NOT NULL,
  TGT_GRUP_ID   VARCHAR2(20 BYTE)               NOT NULL,
  TGT_GRUP_NAME VARCHAR2(128 BYTE),
  TGT_GRUP_RMK  VARCHAR2(500 BYTE),
  REGI_ID       VARCHAR2(20 BYTE),
  REGI_DATE     DATE,
  CHNG_ID       VARCHAR2(20 BYTE),
  CHNG_DATE     DATE,
  PRIMARY KEY (SYS_ID, TGT_GRUP_ID)
);

COMMENT ON TABLE SYS_BORD_GRUP IS '게시판-주소록(그룹)';
COMMENT ON COLUMN SYS_BORD_GRUP.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD_GRUP.BORD_GRUP IS '게시판종류';
COMMENT ON COLUMN SYS_BORD_GRUP.USER_ID IS '사용자 ID';
COMMENT ON COLUMN SYS_BORD_GRUP.TGT_GRUP_ID IS '그룹 ID';
COMMENT ON COLUMN SYS_BORD_GRUP.TGT_GRUP_NAME IS '그룹명';
COMMENT ON COLUMN SYS_BORD_GRUP.TGT_GRUP_RMK IS '비고';
COMMENT ON COLUMN SYS_BORD_GRUP.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD_GRUP.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD_GRUP.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD_GRUP.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_BORD_ITEM
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  TGT_GRUP_ID   VARCHAR2(20 BYTE)               NOT NULL,
  TGT_USER_ID   VARCHAR2(20 BYTE)               NOT NULL,
  TGT_USER_NAME  VARCHAR2(64 BYTE),
  TGT_VNDR_CODE  VARCHAR2(20 BYTE),
  TGT_VNDR_NAME  VARCHAR2(64 BYTE),
  REGI_ID       VARCHAR2(20 BYTE),
  REGI_DATE     DATE,
  CHNG_ID       VARCHAR2(20 BYTE),
  CHNG_DATE     DATE,
  PRIMARY KEY (SYS_ID, TGT_GRUP_ID, TGT_USER_ID)
);

COMMENT ON TABLE SYS_BORD_ITEM IS '게시판-주소록(그룹대상)';
COMMENT ON COLUMN SYS_BORD_ITEM.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_GRUP_ID IS '그룹 ID';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_USER_ID IS '수신자 ID';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_USER_NAME IS '수신자명';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_VNDR_CODE IS '업체코드';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_VNDR_NAME IS '업체명칭';
COMMENT ON COLUMN SYS_BORD_ITEM.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD_ITEM.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD_ITEM.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD_ITEM.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_FILE
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  ATCH_GRUP  VARCHAR2(20 BYTE)                  NOT NULL,
  ATCH_NO    VARCHAR2(30 BYTE)                  NOT NULL,
  FILE_NO    VARCHAR2(20 BYTE)                  NOT NULL,
  FILE_NAME  VARCHAR2(64 BYTE),
  SAVE_NAME  VARCHAR2(256 BYTE),
  FILE_PATH  VARCHAR2(128 BYTE),
  FILE_TYPE  VARCHAR2(30 BYTE),
  FILE_SIZE  NUMBER(10)        DEFAULT 0        NOT NULL,
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY (SYS_ID, ATCH_GRUP, ATCH_NO, FILE_NO)
);

COMMENT ON TABLE SYS_FILE IS '첨부파일';
COMMENT ON COLUMN SYS_FILE.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_FILE.ATCH_GRUP IS '첨부구분(화면,업무)';
COMMENT ON COLUMN SYS_FILE.ATCH_NO IS '첨부번호';
COMMENT ON COLUMN SYS_FILE.FILE_NO IS '파일번호';
COMMENT ON COLUMN SYS_FILE.FILE_NAME IS '파일명';
COMMENT ON COLUMN SYS_FILE.SAVE_NAME IS '저장명칭';
COMMENT ON COLUMN SYS_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN SYS_FILE.FILE_TYPE IS '파일타입';
COMMENT ON COLUMN SYS_FILE.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN SYS_FILE.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_FILE.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_FILE.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_FILE.CHNG_DATE IS '수정일자';


CREATE TABLE SYS_USEC
(
  SYS_ID     VARCHAR2(20 BYTE)   NOT NULL,
  USER_ID    VARCHAR2(20 BYTE)   NOT NULL,
  SECURE_KEY VARCHAR2(100 BYTE)   NOT NULL,
  LOGIN_DATE DATE,  
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY (SYS_ID, USER_ID, SECURE_KEY)
);

COMMENT ON TABLE  SYS_USEC            IS '자동로그인로그';
COMMENT ON COLUMN SYS_USEC.SYS_ID     IS '시스템ID';
COMMENT ON COLUMN SYS_USEC.USER_ID    IS '사용자ID';
COMMENT ON COLUMN SYS_USEC.SECURE_KEY IS '로그인보안키';
COMMENT ON COLUMN SYS_USEC.LOGIN_DATE IS '자동로그인일시';
COMMENT ON COLUMN SYS_USEC.REGI_ID    IS '등록자';
COMMENT ON COLUMN SYS_USEC.REGI_DATE  IS '등록일자';
COMMENT ON COLUMN SYS_USEC.CHNG_ID    IS '수정자';
COMMENT ON COLUMN SYS_USEC.CHNG_DATE  IS '수정일자';


-- 2014.10.07 
CREATE TABLE SYS_SCHD
(
  SYS_ID      VARCHAR2(20 BYTE) NOT NULL,
  SCHD_GRUP   VARCHAR2(20 BYTE) NOT NULL,
  SCHD_SEQ    NUMBER(10)        NOT NULL,
  USER_ID     VARCHAR2(20 BYTE) NOT NULL,
  SCHD_TYPE   VARCHAR2(20 BYTE),
  SCHD_DATE   VARCHAR2(20 BYTE),
  SCHD_TIME   VARCHAR2(20 BYTE),
  SCHD_ENDT   VARCHAR2(20 BYTE),
  SCHD_ENTM   VARCHAR2(20 BYTE),
  SCHD_LINK   VARCHAR2(256 BYTE),
  SCHD_TEXT   VARCHAR2(256 BYTE),
  SCHD_MEMO   VARCHAR2(256 BYTE),
  SCHD_TITLE  VARCHAR2(128 BYTE),
  USE_FLAG    CHAR(1 BYTE),
  REGI_ID     VARCHAR2(20 BYTE),
  REGI_DATE   DATE,
  CHNG_ID     VARCHAR2(20 BYTE),
  CHNG_DATE   DATE,
  PRIMARY KEY (SYS_ID, SCHD_GRUP, SCHD_SEQ)
);

COMMENT ON TABLE  SYS_SCHD            IS '일정관리';
COMMENT ON COLUMN SYS_SCHD.SYS_ID     IS '시스템ID';
COMMENT ON COLUMN SYS_SCHD.USER_ID    IS '사용자ID';
COMMENT ON COLUMN SYS_SCHD.SCHD_GRUP  IS '일정유형';
COMMENT ON COLUMN SYS_SCHD.SCHD_SEQ   IS '일정번호';
COMMENT ON COLUMN SYS_SCHD.SCHD_DATE  IS '일정시작일자';
COMMENT ON COLUMN SYS_SCHD.SCHD_TIME  IS '일정시작시간';
COMMENT ON COLUMN SYS_SCHD.SCHD_ENDT  IS '일정종료일자';
COMMENT ON COLUMN SYS_SCHD.SCHD_ENTM  IS '일정종료시간';
COMMENT ON COLUMN SYS_SCHD.SCHD_TYPE  IS '일정구분(U:개인/C:공유/E:기타)';
COMMENT ON COLUMN SYS_SCHD.SCHD_TEXT  IS '일정내용';
COMMENT ON COLUMN SYS_SCHD.SCHD_MEMO  IS '일정메모';
COMMENT ON COLUMN SYS_SCHD.SCHD_TITLE IS '일정제목';
COMMENT ON COLUMN SYS_SCHD.SCHD_LINK  IS '일정링크';
COMMENT ON COLUMN SYS_SCHD.USE_FLAG   IS '사용유무';
COMMENT ON COLUMN SYS_SCHD.REGI_ID    IS '등록자';
COMMENT ON COLUMN SYS_SCHD.REGI_DATE  IS '등록일자';
COMMENT ON COLUMN SYS_SCHD.CHNG_ID    IS '수정자';
COMMENT ON COLUMN SYS_SCHD.CHNG_DATE  IS '수정일자';

CREATE TABLE SYS_SCHD_PUB
(
  SYS_ID      VARCHAR2(20 BYTE) NOT NULL,
  SCHD_GRUP   VARCHAR2(20 BYTE) NOT NULL,
  SCHD_SEQ    NUMBER(10)        NOT NULL,
  PUB_USER    VARCHAR2(20 BYTE) NOT NULL,
  PUB_TYPE    VARCHAR2(30 BYTE),
  REGI_ID     VARCHAR2(20 BYTE),
  REGI_DATE   DATE,
  CHNG_ID     VARCHAR2(20 BYTE),
  CHNG_DATE   DATE,
  PRIMARY KEY (SYS_ID, SCHD_GRUP, SCHD_SEQ, PUB_USER)
);

COMMENT ON TABLE  SYS_SCHD_PUB              IS '일정관리 공유대상';
COMMENT ON COLUMN SYS_SCHD_PUB.SYS_ID       IS '시스템ID';
COMMENT ON COLUMN SYS_SCHD_PUB.SCHD_GRUP    IS '일정유형';
COMMENT ON COLUMN SYS_SCHD_PUB.SCHD_SEQ     IS '일정번호';
COMMENT ON COLUMN SYS_SCHD_PUB.PUB_USER     IS '공유사용자ID';
COMMENT ON COLUMN SYS_SCHD_PUB.PUB_TYPE     IS '공유타입(A:전체,U:개인)';
COMMENT ON COLUMN SYS_SCHD_PUB.REGI_ID      IS '등록자';
COMMENT ON COLUMN SYS_SCHD_PUB.REGI_DATE    IS '등록일자';
COMMENT ON COLUMN SYS_SCHD_PUB.CHNG_ID      IS '수정자';
COMMENT ON COLUMN SYS_SCHD_PUB.CHNG_DATE    IS '수정일자';

-- 2015.05.04 add
CREATE TABLE SYS_EXCL_FORM
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  EXCL_GRUP  VARCHAR2(20 BYTE)                  NOT NULL,
  FORM_CODE  VARCHAR2(20 BYTE)                  NOT NULL,
  FORM_NAME  VARCHAR2(128 BYTE),
  FORM_DESC  VARCHAR2(256 BYTE),
  TITLE_NO   NUMBER(5)           DEFAULT 1      NOT NULL,
  START_NO   NUMBER(5)           DEFAULT 2      NOT NULL,
  PIVOT_YN   CHAR(1 BYTE)        DEFAULT 'N'    NOT NULL,
  USE_FLAG   CHAR(1 BYTE)        DEFAULT 'Y'    NOT NULL,
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY (SYS_ID, EXCL_GRUP, FORM_CODE)
);
COMMENT ON  TABLE SYS_EXCL_FORM            IS '엑셀맵핑 양식정보';
COMMENT ON COLUMN SYS_EXCL_FORM.SYS_ID     IS '시스템ID';
COMMENT ON COLUMN SYS_EXCL_FORM.EXCL_GRUP  IS '엑셀그룹';
COMMENT ON COLUMN SYS_EXCL_FORM.FORM_CODE  IS '엑셀양식코드';
COMMENT ON COLUMN SYS_EXCL_FORM.FORM_NAME  IS '엑셀양식명칭';
COMMENT ON COLUMN SYS_EXCL_FORM.FORM_DESC  IS '엑셀양식설명';
COMMENT ON COLUMN SYS_EXCL_FORM.TITLE_NO   IS '제목행번호';
COMMENT ON COLUMN SYS_EXCL_FORM.START_NO   IS '시작행번호';
COMMENT ON COLUMN SYS_EXCL_FORM.PIVOT_YN   IS '피벗여부';
COMMENT ON COLUMN SYS_EXCL_FORM.USE_FLAG   IS '사용유무';
COMMENT ON COLUMN SYS_EXCL_FORM.REGI_ID    IS '등록자';
COMMENT ON COLUMN SYS_EXCL_FORM.REGI_DATE  IS '등록일자';
COMMENT ON COLUMN SYS_EXCL_FORM.CHNG_ID    IS '수정자';
COMMENT ON COLUMN SYS_EXCL_FORM.CHNG_DATE  IS '수정일자';

-- 2015.05.04 add
CREATE TABLE SYS_EXCL_ITEM
(
  SYS_ID     VARCHAR2(20  BYTE)                 NOT NULL,
  EXCL_GRUP  VARCHAR2(20  BYTE)                 NOT NULL,
  FORM_CODE  VARCHAR2(20  BYTE)                 NOT NULL,
  ITEM_CODE  VARCHAR2(20  BYTE)                 NOT NULL,
  ITEM_NAME  VARCHAR2(128 BYTE),
  ITEM_TYPE  VARCHAR2(20  BYTE),
  ITEM_DESC  VARCHAR2(256 BYTE),
  ITEM_DEF   VARCHAR2(256 BYTE),
  ITEM_SEQ   NUMBER(5),
  EXCL_CODE  VARCHAR2(20  BYTE),
  USE_FLAG   CHAR(1 BYTE)         DEFAULT 'Y'   NOT NULL,
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY (SYS_ID, EXCL_GRUP, FORM_CODE, ITEM_CODE)
);

COMMENT ON  TABLE SYS_EXCL_ITEM            IS '엑셀맵핑 칼럼정보';
COMMENT ON COLUMN SYS_EXCL_ITEM.SYS_ID     IS '시스템ID';
COMMENT ON COLUMN SYS_EXCL_ITEM.EXCL_GRUP  IS '엑셀그룹';
COMMENT ON COLUMN SYS_EXCL_ITEM.EXCL_CODE  IS '엑셀칼럼';
COMMENT ON COLUMN SYS_EXCL_ITEM.FORM_CODE  IS '엑셀양식코드';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_CODE  IS '맵핑칼럼번호';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_NAME  IS '맵핑칼럼제목';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_TYPE  IS '맵핑칼럼타입';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_DESC  IS '맵핑칼럼설명';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_DEF   IS '맵핑칼럼초기값';
COMMENT ON COLUMN SYS_EXCL_ITEM.ITEM_SEQ   IS '맵핑칼럼순번';
COMMENT ON COLUMN SYS_EXCL_ITEM.USE_FLAG   IS '사용유무';
COMMENT ON COLUMN SYS_EXCL_ITEM.REGI_ID    IS '등록자';
COMMENT ON COLUMN SYS_EXCL_ITEM.REGI_DATE  IS '등록일자';
COMMENT ON COLUMN SYS_EXCL_ITEM.CHNG_ID    IS '수정자';
COMMENT ON COLUMN SYS_EXCL_ITEM.CHNG_DATE  IS '수정일자';
