DROP TABLE SYS_BORD CASCADE CONSTRAINTS;
DROP TABLE SYS_BORD_ADDR CASCADE CONSTRAINTS;
DROP TABLE SYS_BORD_GRUP CASCADE CONSTRAINTS;
DROP TABLE SYS_BORD_ITEM CASCADE CONSTRAINTS;
DROP TABLE SYS_BORD_TGT CASCADE CONSTRAINTS;
DROP TABLE SYS_CODE CASCADE CONSTRAINTS;
DROP TABLE SYS_FILE CASCADE CONSTRAINTS;
DROP TABLE SYS_GPGM CASCADE CONSTRAINTS;
DROP TABLE SYS_GRUP CASCADE CONSTRAINTS;
DROP TABLE SYS_MENU CASCADE CONSTRAINTS;
DROP TABLE SYS_MENU_HOT CASCADE CONSTRAINTS;
DROP TABLE SYS_PROG CASCADE CONSTRAINTS;
DROP TABLE SYS_SCHD CASCADE CONSTRAINTS;
DROP TABLE SYS_SCHD_PUB CASCADE CONSTRAINTS;
DROP TABLE SYS_UGRP CASCADE CONSTRAINTS;
DROP TABLE SYS_ULOG CASCADE CONSTRAINTS;
DROP TABLE SYS_UPGM CASCADE CONSTRAINTS;
DROP TABLE SYS_USEC CASCADE CONSTRAINTS;
DROP TABLE SYS_USER CASCADE CONSTRAINTS;

CREATE TABLE SYS_USER
(
  SYS_ID           VARCHAR2(20 BYTE)            NOT NULL,
  USER_ID          VARCHAR2(20 BYTE)            NOT NULL,
  USER_NAME        VARCHAR2(64 BYTE),
  USER_PWD         VARCHAR2(128 BYTE),
  USER_TYPE        VARCHAR2(20 BYTE),
  ORG_AUTH_CODE    VARCHAR2(20 BYTE),
  SPC_AUTH_CODE    VARCHAR2(20 BYTE),
  COM_CODE         VARCHAR2(20 BYTE),
  COM_NAME         VARCHAR2(128 BYTE),
  EMPL_NO          VARCHAR2(20 BYTE),
  DEPT_CODE        VARCHAR2(20 BYTE),
  DEPT_NAME        VARCHAR2(128 BYTE),
  UPPR_DEPT_CODE   VARCHAR2(20 BYTE),
  USER_TEL         VARCHAR2(20 BYTE),
  USER_HP          VARCHAR2(20 BYTE),
  USER_MAIL        VARCHAR2(64 BYTE),
  USER_REMK        VARCHAR2(128 BYTE),
  PWD_CHNG_DATE    DATE,
  LAST_LOGIN_DATE  DATE,
  LOGIN_FAIL_CNT   NUMBER(3)                    DEFAULT 0                     NOT NULL,
  USE_FLAG         CHAR(1 BYTE),
  REGI_ID          VARCHAR2(20 BYTE),
  REGI_DATE        DATE,
  CHNG_ID          VARCHAR2(20 BYTE),
  CHNG_DATE        DATE,
  PRIMARY KEY
 (SYS_ID, USER_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_USER IS '사용자정보';
COMMENT ON COLUMN SYS_USER.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_USER.USER_ID IS '사용자 ID';
COMMENT ON COLUMN SYS_USER.USER_NAME IS '사용자명';
COMMENT ON COLUMN SYS_USER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN SYS_USER.USER_TYPE IS '사용자유형(내부/업체)';
COMMENT ON COLUMN SYS_USER.ORG_AUTH_CODE IS '기본권한';
COMMENT ON COLUMN SYS_USER.SPC_AUTH_CODE IS '특별권한';
COMMENT ON COLUMN SYS_USER.COM_CODE IS '회사코드';
COMMENT ON COLUMN SYS_USER.COM_NAME IS '회사명';
COMMENT ON COLUMN SYS_USER.EMPL_NO IS '사번';
COMMENT ON COLUMN SYS_USER.DEPT_CODE IS '부서';
COMMENT ON COLUMN SYS_USER.DEPT_NAME IS '부서명';
COMMENT ON COLUMN SYS_USER.UPPR_DEPT_CODE IS '상위부서';
COMMENT ON COLUMN SYS_USER.USER_TEL IS '전화번호';
COMMENT ON COLUMN SYS_USER.USER_HP IS '핸드폰';
COMMENT ON COLUMN SYS_USER.USER_MAIL IS '이메일';
COMMENT ON COLUMN SYS_USER.USER_REMK IS '비고';
COMMENT ON COLUMN SYS_USER.PWD_CHNG_DATE IS '비밀번호변경일자';
COMMENT ON COLUMN SYS_USER.LAST_LOGIN_DATE IS '최종로그인일자';
COMMENT ON COLUMN SYS_USER.LOGIN_FAIL_CNT IS '로그인실패횟수';
COMMENT ON COLUMN SYS_USER.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_USER.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_USER.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_USER.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_USER.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_USEC
(
  SYS_ID      VARCHAR2(20 BYTE)                 NOT NULL,
  USER_ID     VARCHAR2(20 BYTE)                 NOT NULL,
  SECURE_KEY  VARCHAR2(100 BYTE)                NOT NULL,
  LOGIN_DATE  DATE,
  REGI_ID     VARCHAR2(20 BYTE),
  REGI_DATE   DATE,
  CHNG_ID     VARCHAR2(20 BYTE),
  CHNG_DATE   DATE,
  PRIMARY KEY
 (SYS_ID, USER_ID, SECURE_KEY)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_USEC IS '자동로그인로그';
COMMENT ON COLUMN SYS_USEC.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_USEC.USER_ID IS '사용자ID';
COMMENT ON COLUMN SYS_USEC.SECURE_KEY IS '로그인보안키';
COMMENT ON COLUMN SYS_USEC.LOGIN_DATE IS '자동로그인일시';
COMMENT ON COLUMN SYS_USEC.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_USEC.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_USEC.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_USEC.CHNG_DATE IS '수정일자';


CREATE TABLE SYS_UPGM
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  USER_ID    VARCHAR2(20 BYTE)                  NOT NULL,
  PROG_ID    VARCHAR2(128 BYTE)                 NOT NULL,
  TRAN_A     CHAR(1 BYTE),
  TRAN_C     CHAR(1 BYTE),
  TRAN_R     CHAR(1 BYTE),
  TRAN_U     CHAR(1 BYTE),
  TRAN_D     CHAR(1 BYTE),
  TRAN_P     CHAR(1 BYTE),
  TRAN_S     CHAR(1 BYTE),
  TRAN_1     CHAR(1 BYTE),
  TRAN_2     CHAR(1 BYTE),
  TRAN_3     CHAR(1 BYTE),
  TRAN_4     CHAR(1 BYTE),
  TRAN_5     CHAR(1 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, USER_ID, PROG_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_UPGM IS '사용자 화면정보';
COMMENT ON COLUMN SYS_UPGM.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_UPGM.USER_ID IS '사용자 ID';
COMMENT ON COLUMN SYS_UPGM.PROG_ID IS '화면ID';
COMMENT ON COLUMN SYS_UPGM.TRAN_A IS '기본';
COMMENT ON COLUMN SYS_UPGM.TRAN_C IS '등록';
COMMENT ON COLUMN SYS_UPGM.TRAN_R IS '조회';
COMMENT ON COLUMN SYS_UPGM.TRAN_U IS '수정';
COMMENT ON COLUMN SYS_UPGM.TRAN_D IS '삭제';
COMMENT ON COLUMN SYS_UPGM.TRAN_P IS '권한P';
COMMENT ON COLUMN SYS_UPGM.TRAN_S IS '권한S';
COMMENT ON COLUMN SYS_UPGM.TRAN_1 IS '권한1';
COMMENT ON COLUMN SYS_UPGM.TRAN_2 IS '권한2';
COMMENT ON COLUMN SYS_UPGM.TRAN_3 IS '권한3';
COMMENT ON COLUMN SYS_UPGM.TRAN_4 IS '권한4';
COMMENT ON COLUMN SYS_UPGM.TRAN_5 IS '권한5';
COMMENT ON COLUMN SYS_UPGM.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_UPGM.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_UPGM.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_UPGM.CHNG_DATE IS '수정일자';


CREATE TABLE SYS_ULOG
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  ACC_TIME      DATE                            NOT NULL,
  USER_ID       VARCHAR2(20 BYTE)               NOT NULL,
  PROG_ID       VARCHAR2(128 BYTE)              NOT NULL,
  LOGIN_DATE    VARCHAR2(20 BYTE),
  CLIENT_IP     VARCHAR2(30 BYTE),
  CLIENT_NAME   VARCHAR2(64 BYTE),
  CLIENT_AGENT  VARCHAR2(2048 BYTE),
  PRIMARY KEY
 (SYS_ID, ACC_TIME, USER_ID, PROG_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_ULOG IS '사용로그';
COMMENT ON COLUMN SYS_ULOG.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_ULOG.ACC_TIME IS '접근일시';
COMMENT ON COLUMN SYS_ULOG.USER_ID IS '사용ID';
COMMENT ON COLUMN SYS_ULOG.PROG_ID IS '화면ID';
COMMENT ON COLUMN SYS_ULOG.LOGIN_DATE IS '로그인날짜';
COMMENT ON COLUMN SYS_ULOG.CLIENT_IP IS 'CLIENT IP';
COMMENT ON COLUMN SYS_ULOG.CLIENT_NAME IS 'CLIENT 컴퓨터명';
COMMENT ON COLUMN SYS_ULOG.CLIENT_AGENT IS 'CLIENT 브라우저';


CREATE TABLE SYS_UGRP
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  USER_ID    VARCHAR2(20 BYTE)                  NOT NULL,
  GROUP_ID   VARCHAR2(20 BYTE)                  NOT NULL,
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, USER_ID, GROUP_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_UGRP IS '사용자그룹정보';
COMMENT ON COLUMN SYS_UGRP.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_UGRP.USER_ID IS '사용자 ID';
COMMENT ON COLUMN SYS_UGRP.GROUP_ID IS '그룹ID';
COMMENT ON COLUMN SYS_UGRP.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_UGRP.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_UGRP.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_UGRP.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_SCHD_PUB
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  SCHD_GRUP  VARCHAR2(20 BYTE)                  NOT NULL,
  SCHD_SEQ   NUMBER(10)                         NOT NULL,
  PUB_USER   VARCHAR2(20 BYTE)                  NOT NULL,
  PUB_TYPE   VARCHAR2(30 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, SCHD_GRUP, SCHD_SEQ, PUB_USER)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_SCHD_PUB IS '일정관리 공유대상';
COMMENT ON COLUMN SYS_SCHD_PUB.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_SCHD_PUB.SCHD_GRUP IS '일정유형';
COMMENT ON COLUMN SYS_SCHD_PUB.SCHD_SEQ IS '일정번호';
COMMENT ON COLUMN SYS_SCHD_PUB.PUB_USER IS '공유사용자ID';
COMMENT ON COLUMN SYS_SCHD_PUB.PUB_TYPE IS '공유타입(A:전체,U:개인)';
COMMENT ON COLUMN SYS_SCHD_PUB.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_SCHD_PUB.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_SCHD_PUB.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_SCHD_PUB.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_SCHD
(
  SYS_ID      VARCHAR2(20 BYTE)                 NOT NULL,
  SCHD_GRUP   VARCHAR2(20 BYTE)                 NOT NULL,
  SCHD_SEQ    NUMBER(10)                        NOT NULL,
  USER_ID     VARCHAR2(20 BYTE)                 NOT NULL,
  SCHD_TYPE   VARCHAR2(20 BYTE),
  SCHD_DATE   VARCHAR2(20 BYTE),
  SCHD_TIME   VARCHAR2(20 BYTE),
  SCHD_ENDT   VARCHAR2(20 BYTE),
  SCHD_ENTM   VARCHAR2(20 BYTE),
  SCHD_LINK   VARCHAR2(256 BYTE),
  SCHD_TEXT   VARCHAR2(256 BYTE),
  SCHD_MEMO   VARCHAR2(256 BYTE),
  SCHD_TITLE  VARCHAR2(128 BYTE),
  USE_FLAG    CHAR(1 BYTE),
  REGI_ID     VARCHAR2(20 BYTE),
  REGI_DATE   DATE,
  CHNG_ID     VARCHAR2(20 BYTE),
  CHNG_DATE   DATE,
  PRIMARY KEY
 (SYS_ID, SCHD_GRUP, SCHD_SEQ)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_SCHD IS '일정관리';
COMMENT ON COLUMN SYS_SCHD.SCHD_TEXT IS '일정내용';
COMMENT ON COLUMN SYS_SCHD.SCHD_MEMO IS '일정메모';
COMMENT ON COLUMN SYS_SCHD.SCHD_TITLE IS '일정제목';
COMMENT ON COLUMN SYS_SCHD.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_SCHD.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_SCHD.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_SCHD.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_SCHD.CHNG_DATE IS '수정일자';
COMMENT ON COLUMN SYS_SCHD.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_SCHD.SCHD_GRUP IS '일정유형';
COMMENT ON COLUMN SYS_SCHD.SCHD_SEQ IS '일정번호';
COMMENT ON COLUMN SYS_SCHD.USER_ID IS '사용자ID';
COMMENT ON COLUMN SYS_SCHD.SCHD_TYPE IS '일정구분(U:개인/C:공유/E:기타)';
COMMENT ON COLUMN SYS_SCHD.SCHD_DATE IS '일정시작일자';
COMMENT ON COLUMN SYS_SCHD.SCHD_TIME IS '일정시작시간';
COMMENT ON COLUMN SYS_SCHD.SCHD_ENDT IS '일정종료일자';
COMMENT ON COLUMN SYS_SCHD.SCHD_ENTM IS '일정종료시간';
COMMENT ON COLUMN SYS_SCHD.SCHD_LINK IS '일정링크';

CREATE TABLE SYS_PROG
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  PROG_ID    VARCHAR2(128 BYTE)                 NOT NULL,
  PROG_NAME  VARCHAR2(128 BYTE),
  PROG_TYPE  VARCHAR2(20 BYTE),
  TRAN_A     CHAR(1 BYTE),
  TRAN_C     CHAR(1 BYTE),
  TRAN_R     CHAR(1 BYTE),
  TRAN_U     CHAR(1 BYTE),
  TRAN_D     CHAR(1 BYTE),
  TRAN_P     CHAR(1 BYTE),
  TRAN_S     CHAR(1 BYTE),
  TRAN_1     CHAR(1 BYTE),
  TRAN_2     CHAR(1 BYTE),
  TRAN_3     CHAR(1 BYTE),
  TRAN_4     CHAR(1 BYTE),
  TRAN_5     CHAR(1 BYTE),
  SYS_LOC    VARCHAR2(128 BYTE),
  USE_FLAG   CHAR(1 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, PROG_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_PROG IS '화면정보';
COMMENT ON COLUMN SYS_PROG.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_PROG.CHNG_DATE IS '수정일자';
COMMENT ON COLUMN SYS_PROG.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_PROG.PROG_ID IS '화면ID';
COMMENT ON COLUMN SYS_PROG.PROG_NAME IS '화면명';
COMMENT ON COLUMN SYS_PROG.PROG_TYPE IS '유형';
COMMENT ON COLUMN SYS_PROG.TRAN_A IS '기본';
COMMENT ON COLUMN SYS_PROG.TRAN_C IS '등록';
COMMENT ON COLUMN SYS_PROG.TRAN_R IS '조회';
COMMENT ON COLUMN SYS_PROG.TRAN_U IS '수정';
COMMENT ON COLUMN SYS_PROG.TRAN_D IS '삭제';
COMMENT ON COLUMN SYS_PROG.TRAN_P IS '권한P';
COMMENT ON COLUMN SYS_PROG.TRAN_S IS '권한S';
COMMENT ON COLUMN SYS_PROG.TRAN_1 IS '권한1';
COMMENT ON COLUMN SYS_PROG.TRAN_2 IS '권한2';
COMMENT ON COLUMN SYS_PROG.TRAN_3 IS '권한3';
COMMENT ON COLUMN SYS_PROG.TRAN_4 IS '권한4';
COMMENT ON COLUMN SYS_PROG.TRAN_5 IS '권한5';
COMMENT ON COLUMN SYS_PROG.SYS_LOC IS '상태';
COMMENT ON COLUMN SYS_PROG.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_PROG.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_PROG.REGI_DATE IS '등록일자';

CREATE TABLE SYS_MENU_HOT
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  USER_ID    VARCHAR2(20 BYTE)                  NOT NULL,
  MENU_KEY   VARCHAR2(5 BYTE)                   NOT NULL,
  SORT_SEQ   NUMBER(5)                          DEFAULT 0                     NOT NULL,
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, USER_ID, MENU_KEY)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_MENU_HOT IS 'HOT-메뉴구성정보';
COMMENT ON COLUMN SYS_MENU_HOT.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_MENU_HOT.USER_ID IS '사용자 ID( COMM or ID)';
COMMENT ON COLUMN SYS_MENU_HOT.MENU_KEY IS '메뉴ID';
COMMENT ON COLUMN SYS_MENU_HOT.SORT_SEQ IS '순서';
COMMENT ON COLUMN SYS_MENU_HOT.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_MENU_HOT.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_MENU_HOT.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_MENU_HOT.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_MENU
(
  SYS_ID      VARCHAR2(20 BYTE)                 NOT NULL,
  MENU_KEY    VARCHAR2(5 BYTE)                  NOT NULL,
  MENU_LEVEL  NUMBER(2)                         DEFAULT 0                     NOT NULL,
  MENU_DESC   VARCHAR2(128 BYTE),
  MENU_DIR    VARCHAR2(64 BYTE),
  MENU_URL    VARCHAR2(64 BYTE),
  PARENT_KEY  VARCHAR2(5 BYTE),
  CHILD_YN    CHAR(1 BYTE),
  PROC_TYPE   VARCHAR2(1 BYTE),
  ACTION_YN   VARCHAR2(1 BYTE),
  ICON_CLS    VARCHAR2(20 BYTE),
  MENU_SEQ    NUMBER(5)                         DEFAULT 0                     NOT NULL,
  SEPA_TEXT   VARCHAR2(20 BYTE),
  USE_FLAG    CHAR(1 BYTE),
  ENABLE_YN   CHAR(1 BYTE),
  REGI_ID     VARCHAR2(20 BYTE),
  REGI_DATE   DATE,
  CHNG_ID     VARCHAR2(20 BYTE),
  CHNG_DATE   DATE,
  PRIMARY KEY
 (SYS_ID, MENU_KEY)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_MENU IS '메뉴구성정보';
COMMENT ON COLUMN SYS_MENU.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_MENU.MENU_KEY IS '메뉴ID';
COMMENT ON COLUMN SYS_MENU.MENU_LEVEL IS '메뉴레벨';
COMMENT ON COLUMN SYS_MENU.MENU_DESC IS '메뉴명';
COMMENT ON COLUMN SYS_MENU.MENU_DIR IS '메뉴DIR';
COMMENT ON COLUMN SYS_MENU.MENU_URL IS '메뉴URL';
COMMENT ON COLUMN SYS_MENU.PARENT_KEY IS '상위메뉴ID';
COMMENT ON COLUMN SYS_MENU.CHILD_YN IS '하위보유여부';
COMMENT ON COLUMN SYS_MENU.PROC_TYPE IS '화면구현여부';
COMMENT ON COLUMN SYS_MENU.ACTION_YN IS '페이지유무';
COMMENT ON COLUMN SYS_MENU.ICON_CLS IS '아이콘클래스';
COMMENT ON COLUMN SYS_MENU.MENU_SEQ IS '메뉴순서';
COMMENT ON COLUMN SYS_MENU.SEPA_TEXT IS '구분자';
COMMENT ON COLUMN SYS_MENU.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_MENU.ENABLE_YN IS '활성화여부';
COMMENT ON COLUMN SYS_MENU.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_MENU.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_MENU.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_MENU.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_GRUP
(
  SYS_ID      VARCHAR2(20 BYTE)                 NOT NULL,
  GROUP_ID    VARCHAR2(20 BYTE)                 NOT NULL,
  GROUP_NAME  VARCHAR2(128 BYTE),
  REGI_ID     VARCHAR2(20 BYTE),
  REGI_DATE   DATE,
  CHNG_ID     VARCHAR2(20 BYTE),
  CHNG_DATE   DATE,
  PRIMARY KEY
 (SYS_ID, GROUP_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_GRUP IS '그룹정보';
COMMENT ON COLUMN SYS_GRUP.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_GRUP.GROUP_ID IS '그룹ID';
COMMENT ON COLUMN SYS_GRUP.GROUP_NAME IS '그룹명';
COMMENT ON COLUMN SYS_GRUP.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_GRUP.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_GRUP.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_GRUP.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_GPGM
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  GROUP_ID   VARCHAR2(20 BYTE)                  NOT NULL,
  PROG_ID    VARCHAR2(128 BYTE)                 NOT NULL,
  TRAN_A     CHAR(1 BYTE),
  TRAN_C     CHAR(1 BYTE),
  TRAN_R     CHAR(1 BYTE),
  TRAN_U     CHAR(1 BYTE),
  TRAN_D     CHAR(1 BYTE),
  TRAN_P     CHAR(1 BYTE),
  TRAN_S     CHAR(1 BYTE),
  TRAN_1     CHAR(1 BYTE),
  TRAN_2     CHAR(1 BYTE),
  TRAN_3     CHAR(1 BYTE),
  TRAN_4     CHAR(1 BYTE),
  TRAN_5     CHAR(1 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, GROUP_ID, PROG_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_GPGM IS '그룹별 화면정보';
COMMENT ON COLUMN SYS_GPGM.TRAN_D IS '삭제';
COMMENT ON COLUMN SYS_GPGM.TRAN_P IS '권한P';
COMMENT ON COLUMN SYS_GPGM.TRAN_S IS '권한S';
COMMENT ON COLUMN SYS_GPGM.TRAN_1 IS '권한1';
COMMENT ON COLUMN SYS_GPGM.TRAN_2 IS '권한2';
COMMENT ON COLUMN SYS_GPGM.TRAN_3 IS '권한3';
COMMENT ON COLUMN SYS_GPGM.TRAN_4 IS '권한4';
COMMENT ON COLUMN SYS_GPGM.TRAN_5 IS '권한5';
COMMENT ON COLUMN SYS_GPGM.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_GPGM.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_GPGM.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_GPGM.CHNG_DATE IS '수정일자';
COMMENT ON COLUMN SYS_GPGM.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_GPGM.GROUP_ID IS '그룹ID';
COMMENT ON COLUMN SYS_GPGM.PROG_ID IS '화면ID';
COMMENT ON COLUMN SYS_GPGM.TRAN_A IS '기본';
COMMENT ON COLUMN SYS_GPGM.TRAN_C IS '등록';
COMMENT ON COLUMN SYS_GPGM.TRAN_R IS '조회';
COMMENT ON COLUMN SYS_GPGM.TRAN_U IS '수정';

CREATE TABLE SYS_FILE
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  ATCH_GRUP  VARCHAR2(20 BYTE)                  NOT NULL,
  ATCH_NO    VARCHAR2(30 BYTE)                  NOT NULL,
  FILE_NO    VARCHAR2(20 BYTE)                  NOT NULL,
  FILE_NAME  VARCHAR2(64 BYTE),
  SAVE_NAME  VARCHAR2(256 BYTE),
  FILE_PATH  VARCHAR2(128 BYTE),
  FILE_TYPE  VARCHAR2(128 BYTE),
  FILE_SIZE  NUMBER(10)                         DEFAULT 0                     NOT NULL,
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, ATCH_GRUP, ATCH_NO, FILE_NO)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_FILE IS '첨부파일';
COMMENT ON COLUMN SYS_FILE.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_FILE.ATCH_GRUP IS '첨부구분(화면,업무)';
COMMENT ON COLUMN SYS_FILE.ATCH_NO IS '첨부번호';
COMMENT ON COLUMN SYS_FILE.FILE_NO IS '파일번호';
COMMENT ON COLUMN SYS_FILE.FILE_NAME IS '파일명';
COMMENT ON COLUMN SYS_FILE.SAVE_NAME IS '저장명칭';
COMMENT ON COLUMN SYS_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN SYS_FILE.FILE_TYPE IS '파일타입';
COMMENT ON COLUMN SYS_FILE.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN SYS_FILE.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_FILE.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_FILE.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_FILE.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_CODE
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_GRUP  VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_CD    VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_NAME  VARCHAR2(128 BYTE),
  CODE_DESC  VARCHAR2(256 BYTE),
  SORT_SEQ   NUMBER(5)                          DEFAULT 0                     NOT NULL,
  USE_FLAG   CHAR(1 BYTE),
  EXT_CHR01  VARCHAR2(128 BYTE),
  EXT_CHR02  VARCHAR2(128 BYTE),
  EXT_CHR03  VARCHAR2(128 BYTE),
  EXT_CHR04  VARCHAR2(128 BYTE),
  EXT_CHR05  VARCHAR2(128 BYTE),
  EXT_CHR06  VARCHAR2(128 BYTE),
  EXT_CHR07  VARCHAR2(128 BYTE),
  EXT_CHR08  VARCHAR2(128 BYTE),
  EXT_CHR09  VARCHAR2(128 BYTE),
  EXT_CHR10  VARCHAR2(128 BYTE),
  EXT_NUM01  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM02  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM03  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM04  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM05  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_TEXT   VARCHAR2(512 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, CODE_GRUP, CODE_CD)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_CODE IS '코드관리';
COMMENT ON COLUMN SYS_CODE.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_CODE.CODE_GRUP IS '코드그룹';
COMMENT ON COLUMN SYS_CODE.CODE_CD IS '코드';
COMMENT ON COLUMN SYS_CODE.CODE_NAME IS '코드명칭';
COMMENT ON COLUMN SYS_CODE.CODE_DESC IS '코드설명';
COMMENT ON COLUMN SYS_CODE.SORT_SEQ IS '순서';
COMMENT ON COLUMN SYS_CODE.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_CODE.EXT_CHR01 IS '문자속성01';
COMMENT ON COLUMN SYS_CODE.EXT_CHR02 IS '문자속성02';
COMMENT ON COLUMN SYS_CODE.EXT_CHR03 IS '문자속성03';
COMMENT ON COLUMN SYS_CODE.EXT_CHR04 IS '문자속성04';
COMMENT ON COLUMN SYS_CODE.EXT_CHR05 IS '문자속성05';
COMMENT ON COLUMN SYS_CODE.EXT_CHR06 IS '문자속성06';
COMMENT ON COLUMN SYS_CODE.EXT_CHR07 IS '문자속성07';
COMMENT ON COLUMN SYS_CODE.EXT_CHR08 IS '문자속성08';
COMMENT ON COLUMN SYS_CODE.EXT_CHR09 IS '문자속성09';
COMMENT ON COLUMN SYS_CODE.EXT_CHR10 IS '문자속성10';
COMMENT ON COLUMN SYS_CODE.EXT_NUM01 IS '숫자속성01';
COMMENT ON COLUMN SYS_CODE.EXT_NUM02 IS '숫자속성02';
COMMENT ON COLUMN SYS_CODE.EXT_NUM03 IS '숫자속성03';
COMMENT ON COLUMN SYS_CODE.EXT_NUM04 IS '숫자속성04';
COMMENT ON COLUMN SYS_CODE.EXT_NUM05 IS '숫자속성05';
COMMENT ON COLUMN SYS_CODE.EXT_TEXT IS '기타정보';
COMMENT ON COLUMN SYS_CODE.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_CODE.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_CODE.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_CODE.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_BORD_TGT
(
  SYS_ID       VARCHAR2(20 BYTE)                NOT NULL,
  BORD_GRUP    VARCHAR2(20 BYTE)                NOT NULL,
  BORD_NO      VARCHAR2(30 BYTE)                NOT NULL,
  TGT_USER_ID  VARCHAR2(20 BYTE)                NOT NULL,
  VNDR_CODE    VARCHAR2(20 BYTE),
  VNDR_NAME    VARCHAR2(64 BYTE),
  READ_DATE    DATE,
  SAVE_IDX     CHAR(1 BYTE),
  USE_FLAG     CHAR(1 BYTE),
  REGI_ID      VARCHAR2(20 BYTE),
  REGI_DATE    DATE,
  CHNG_ID      VARCHAR2(20 BYTE),
  CHNG_DATE    DATE,
  PRIMARY KEY
 (SYS_ID, BORD_GRUP, BORD_NO, TGT_USER_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_BORD_TGT IS '게시판-게시대상';
COMMENT ON COLUMN SYS_BORD_TGT.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD_TGT.BORD_GRUP IS '게시판 종류';
COMMENT ON COLUMN SYS_BORD_TGT.BORD_NO IS '게시물 번호';
COMMENT ON COLUMN SYS_BORD_TGT.TGT_USER_ID IS '게시대상 ID';
COMMENT ON COLUMN SYS_BORD_TGT.VNDR_CODE IS '업체코드';
COMMENT ON COLUMN SYS_BORD_TGT.VNDR_NAME IS '업체명칭';
COMMENT ON COLUMN SYS_BORD_TGT.READ_DATE IS '확인일시';
COMMENT ON COLUMN SYS_BORD_TGT.SAVE_IDX IS '보관여부';
COMMENT ON COLUMN SYS_BORD_TGT.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_BORD_TGT.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD_TGT.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD_TGT.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD_TGT.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_BORD_ITEM
(
  SYS_ID         VARCHAR2(20 BYTE)              NOT NULL,
  TGT_GRUP_ID    VARCHAR2(20 BYTE)              NOT NULL,
  TGT_USER_ID    VARCHAR2(20 BYTE)              NOT NULL,
  TGT_USER_NAME  VARCHAR2(64 BYTE),
  TGT_VNDR_CODE  VARCHAR2(20 BYTE),
  TGT_VNDR_NAME  VARCHAR2(64 BYTE),
  REGI_ID        VARCHAR2(20 BYTE),
  REGI_DATE      DATE,
  CHNG_ID        VARCHAR2(20 BYTE),
  CHNG_DATE      DATE,
  PRIMARY KEY
 (SYS_ID, TGT_GRUP_ID, TGT_USER_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_BORD_ITEM IS '게시판-주소록(그룹대상)';
COMMENT ON COLUMN SYS_BORD_ITEM.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_GRUP_ID IS '그룹 ID';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_USER_ID IS '수신자 ID';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_USER_NAME IS '수신자명';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_VNDR_CODE IS '업체코드';
COMMENT ON COLUMN SYS_BORD_ITEM.TGT_VNDR_NAME IS '업체명칭';
COMMENT ON COLUMN SYS_BORD_ITEM.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD_ITEM.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD_ITEM.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD_ITEM.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_BORD_GRUP
(
  SYS_ID         VARCHAR2(20 BYTE)              NOT NULL,
  BORD_GRUP      VARCHAR2(20 BYTE)              NOT NULL,
  USER_ID        VARCHAR2(20 BYTE)              NOT NULL,
  TGT_GRUP_ID    VARCHAR2(20 BYTE)              NOT NULL,
  TGT_GRUP_NAME  VARCHAR2(128 BYTE),
  TGT_GRUP_RMK   VARCHAR2(500 BYTE),
  REGI_ID        VARCHAR2(20 BYTE),
  REGI_DATE      DATE,
  CHNG_ID        VARCHAR2(20 BYTE),
  CHNG_DATE      DATE,
  PRIMARY KEY
 (SYS_ID, TGT_GRUP_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_BORD_GRUP IS '게시판-주소록(그룹)';
COMMENT ON COLUMN SYS_BORD_GRUP.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD_GRUP.BORD_GRUP IS '게시판종류';
COMMENT ON COLUMN SYS_BORD_GRUP.USER_ID IS '사용자 ID';
COMMENT ON COLUMN SYS_BORD_GRUP.TGT_GRUP_ID IS '그룹 ID';
COMMENT ON COLUMN SYS_BORD_GRUP.TGT_GRUP_NAME IS '그룹명';
COMMENT ON COLUMN SYS_BORD_GRUP.TGT_GRUP_RMK IS '비고';
COMMENT ON COLUMN SYS_BORD_GRUP.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD_GRUP.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD_GRUP.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD_GRUP.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_BORD_ADDR
(
  SYS_ID         VARCHAR2(20 BYTE)              NOT NULL,
  BORD_GRUP      VARCHAR2(20 BYTE)              NOT NULL,
  USER_ID        VARCHAR2(20 BYTE)              NOT NULL,
  TGT_USER_ID    VARCHAR2(20 BYTE)              NOT NULL,
  TGT_USER_NAME  VARCHAR2(64 BYTE),
  TGT_VNDR_CODE  VARCHAR2(20 BYTE),
  TGT_VNDR_NAME  VARCHAR2(64 BYTE),
  TGT_USER_RMK   VARCHAR2(128 BYTE),
  REGI_ID        VARCHAR2(20 BYTE),
  REGI_DATE      DATE,
  CHNG_ID        VARCHAR2(20 BYTE),
  CHNG_DATE      DATE,
  PRIMARY KEY
 (SYS_ID, BORD_GRUP, USER_ID, TGT_USER_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_BORD_ADDR IS '게시판-주소록';
COMMENT ON COLUMN SYS_BORD_ADDR.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD_ADDR.BORD_GRUP IS '게시판 종류';
COMMENT ON COLUMN SYS_BORD_ADDR.USER_ID IS '사용자 ID';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_USER_ID IS '수신자 ID';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_USER_NAME IS '수신자명';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_VNDR_CODE IS '업체코드';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_VNDR_NAME IS '업체명칭';
COMMENT ON COLUMN SYS_BORD_ADDR.TGT_USER_RMK IS '비고';
COMMENT ON COLUMN SYS_BORD_ADDR.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD_ADDR.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD_ADDR.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD_ADDR.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_BORD
(
  SYS_ID      VARCHAR2(20 BYTE)                 NOT NULL,
  BORD_GRUP   VARCHAR2(20 BYTE)                 NOT NULL,
  BORD_NO     VARCHAR2(30 BYTE)                 NOT NULL,
  BORD_TITLE  VARCHAR2(128 BYTE),
  BORD_TEXT   VARCHAR2(4000 BYTE),
  BORD_TYPE   VARCHAR2(20 BYTE),
  BORD_BGN    VARCHAR2(10 BYTE),
  BORD_END    VARCHAR2(10 BYTE),
  READ_CNT    NUMBER(7)                         DEFAULT 0                     NOT NULL,
  BORD_SEQ    NUMBER(10)                        DEFAULT 0                     NOT NULL,
  USE_FLAG    CHAR(1 BYTE),
  REGI_ID     VARCHAR2(20 BYTE),
  REGI_DATE   DATE,
  CHNG_ID     VARCHAR2(20 BYTE),
  CHNG_DATE   DATE,
  BORD_PNO    VARCHAR2(30 BYTE),
  PRIMARY KEY
 (SYS_ID, BORD_GRUP, BORD_NO)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_BORD IS '게시판';
COMMENT ON COLUMN SYS_BORD.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_BORD.BORD_GRUP IS '게시판 종류';
COMMENT ON COLUMN SYS_BORD.BORD_NO IS '게시물 번호';
COMMENT ON COLUMN SYS_BORD.BORD_TITLE IS '게시물 제목';
COMMENT ON COLUMN SYS_BORD.BORD_TEXT IS '게시물 내용';
COMMENT ON COLUMN SYS_BORD.BORD_TYPE IS '게시타입';
COMMENT ON COLUMN SYS_BORD.BORD_BGN IS '게시 시작일';
COMMENT ON COLUMN SYS_BORD.BORD_END IS '게시 종료일';
COMMENT ON COLUMN SYS_BORD.READ_CNT IS '조회수';
COMMENT ON COLUMN SYS_BORD.BORD_SEQ IS '조회순서';
COMMENT ON COLUMN SYS_BORD.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_BORD.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_BORD.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_BORD.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_BORD.CHNG_DATE IS '수정일자';
COMMENT ON COLUMN SYS_BORD.BORD_PNO IS '게시물 상위번호';

DROP VIEW V_SYS_AUTH;

/* Formatted on 2014-10-17 오후 6:11:22 (QP5 v5.115.810.9015) */
CREATE OR REPLACE FORCE VIEW V_SYS_AUTH
(
   SYS_ID,
   USER_ID,
   AUTH_TYPE,
   PROG_ID,
   TRAN_A,
   TRAN_C,
   TRAN_R,
   TRAN_U,
   TRAN_D,
   TRAN_P,
   TRAN_S,
   TRAN_1,
   TRAN_2,
   TRAN_3,
   TRAN_4,
   TRAN_5
)
AS
   SELECT   X.SYS_ID,
            X.USER_ID,
            DECODE (X.AUTH_TYPE,
                    '10.USER', 'USER',
                    '20.GROUP', 'GROUP',
                    'DEFAULT'),
            X.PROG_ID,
            X.TRAN_A,
            X.TRAN_C,
            X.TRAN_R,
            X.TRAN_U,
            X.TRAN_D,
            X.TRAN_P,
            X.TRAN_S,
            X.TRAN_1,
            X.TRAN_2,
            X.TRAN_3,
            X.TRAN_4,
            X.TRAN_5
     FROM   (SELECT   A.*
               FROM   (SELECT   ROW_NUMBER ()
                                   OVER (
                                      PARTITION BY A.SYS_ID,
                                                   A.USER_ID,
                                                   A.PROG_ID
                                      ORDER BY A.SYS_ID,
                                               A.USER_ID,
                                               A.PROG_ID,
                                               A.AUTH_TYPE
                                   )
                                   AUTH_SEQ,
                                A.*
                         FROM   (SELECT   A.SYS_ID,
                                          A.USER_ID,
                                          '10.USER' AUTH_TYPE,
                                          A.PROG_ID,
                                          A.TRAN_A,
                                          A.TRAN_C,
                                          A.TRAN_R,
                                          A.TRAN_U,
                                          A.TRAN_D,
                                          A.TRAN_P,
                                          A.TRAN_S,
                                          A.TRAN_1,
                                          A.TRAN_2,
                                          A.TRAN_3,
                                          A.TRAN_4,
                                          A.TRAN_5
                                   FROM   SYS_UPGM A
                                 UNION
                                   SELECT   A.SYS_ID,
                                            B.USER_ID,
                                            '20.GROUP' AUTH_TYPE,
                                            A.PROG_ID,
                                            MAX (A.TRAN_A),
                                            MAX (A.TRAN_C),
                                            MAX (A.TRAN_R),
                                            MAX (A.TRAN_U),
                                            MAX (A.TRAN_D),
                                            MAX (A.TRAN_P),
                                            MAX (A.TRAN_S),
                                            MAX (A.TRAN_1),
                                            MAX (A.TRAN_2),
                                            MAX (A.TRAN_3),
                                            MAX (A.TRAN_4),
                                            MAX (A.TRAN_5)
                                     FROM   SYS_GPGM A, SYS_UGRP B
                                    WHERE   A.SYS_ID = B.SYS_ID
                                            AND A.GROUP_ID = B.GROUP_ID
                                 GROUP BY   A.SYS_ID, B.USER_ID, A.PROG_ID
                                 UNION
                                 SELECT   A.SYS_ID,
                                          B.USER_ID,
                                          '30.DEFAULT' AUTH_TYPE,
                                          A.PROG_ID,
                                          '0' TRAN_A,
                                          '0' TRAN_C,
                                          '0' TRAN_R,
                                          '0' TRAN_U,
                                          '0' TRAN_D,
                                          '0' TRAN_P,
                                          '0' TRAN_S,
                                          '0' TRAN_1,
                                          '0' TRAN_2,
                                          '0' TRAN_3,
                                          '0' TRAN_4,
                                          '0' TRAN_5
                                   FROM   SYS_PROG A, SYS_USER B
                                  WHERE   A.SYS_ID = B.SYS_ID) A) A
              WHERE   A.AUTH_SEQ = 1) X;


