CREATE TABLE VNDR_MAST
(
  SYS_ID              VARCHAR2(20 BYTE)         NOT NULL,
  VNDR_CODE           VARCHAR2(20 BYTE)         NOT NULL,
  VNDR_NAME           VARCHAR2(128 BYTE),
  VNDR_NAME_ABBR      VARCHAR2(128 BYTE),
  VNDR_NAME_ENG       VARCHAR2(128 BYTE),
  VNDR_NAME_ENG_ABBR  VARCHAR2(128 BYTE),
  VNDR_TYPE           VARCHAR2(20 BYTE),
  VNDR_CNTL_USER      VARCHAR2(20 BYTE),
  VNDR_LEVL           VARCHAR2(20 BYTE),
  VNDR_BIZ_NO         VARCHAR2(20 BYTE),
  PREV_VNDR_CODE      VARCHAR2(20 BYTE),
  TRAD_STAT           VARCHAR2(20 BYTE),
  TRAD_BGN_DATE       VARCHAR2(10 BYTE),
  TRAD_END_DATE       VARCHAR2(10 BYTE),
  COMP_TYPE           VARCHAR2(20 BYTE),
  COMP_CHAR           VARCHAR2(20 BYTE),
  COMP_IND            VARCHAR2(20 BYTE),
  MAIN_PROD_ITEM      VARCHAR2(64 BYTE),
  MAIN_TRAD_ITEM      VARCHAR2(64 BYTE),
  COMP_EST_DATE       VARCHAR2(10 BYTE),
  ADMN_PERS           NUMBER(5)                 DEFAULT 0                     NOT NULL,
  LABR_PERS           NUMBER(5)                 DEFAULT 0                     NOT NULL,
  TOT_EMPL            NUMBER(5)                 DEFAULT 0                     NOT NULL,
  COMP_ADDR           VARCHAR2(128 BYTE),
  COMP_LAND           NUMBER(7)                 DEFAULT 0                     NOT NULL,
  COMP_BULD           NUMBER(7)                 DEFAULT 0                     NOT NULL,
  COMP_OWNR           VARCHAR2(20 BYTE),
  COMP_TEL            VARCHAR2(20 BYTE),
  PLNT_ADDR           VARCHAR2(128 BYTE),
  PLNT_LAND           NUMBER(7)                 DEFAULT 0                     NOT NULL,
  PLNT_BULD           NUMBER(7)                 DEFAULT 0                     NOT NULL,
  PLNT_OWNR           VARCHAR2(20 BYTE),
  PLNT_TEL            VARCHAR2(20 BYTE),
  CEO_NAME            VARCHAR2(64 BYTE),
  CEO_SNUM            VARCHAR2(20 BYTE),
  CEO_EDU             VARCHAR2(64 BYTE),
  CEO_TEL             VARCHAR2(20 BYTE),
  COMP_MEMO           VARCHAR2(256 BYTE),
  REGI_ID             VARCHAR2(20 BYTE),
  REGI_DATE           DATE,
  CHNG_ID             VARCHAR2(20 BYTE),
  CHNG_DATE           DATE,
  PRIMARY KEY
 (SYS_ID, VNDR_CODE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE VNDR_MAST IS 'Vendor Master';
COMMENT ON COLUMN VNDR_MAST.SYS_ID IS '시스템ID';
COMMENT ON COLUMN VNDR_MAST.VNDR_CODE IS '업체코드';
COMMENT ON COLUMN VNDR_MAST.VNDR_NAME IS '업체명칭';
COMMENT ON COLUMN VNDR_MAST.VNDR_NAME_ABBR IS '업체명칭(약칭)';
COMMENT ON COLUMN VNDR_MAST.VNDR_NAME_ENG IS '업체명칭(영문)';
COMMENT ON COLUMN VNDR_MAST.VNDR_NAME_ENG_ABBR IS '업체명칭(영문약칭)';
COMMENT ON COLUMN VNDR_MAST.VNDR_TYPE IS '업체구분(CUST/VNDR)';
COMMENT ON COLUMN VNDR_MAST.VNDR_CNTL_USER IS '관리담당(내부, ID->메일)';
COMMENT ON COLUMN VNDR_MAST.VNDR_LEVL IS '관리등급';
COMMENT ON COLUMN VNDR_MAST.VNDR_BIZ_NO IS '사업자번호';
COMMENT ON COLUMN VNDR_MAST.PREV_VNDR_CODE IS '이전업체코드';
COMMENT ON COLUMN VNDR_MAST.TRAD_STAT IS '거래상태(거래중/거래종료)';
COMMENT ON COLUMN VNDR_MAST.TRAD_BGN_DATE IS '거래시작일';
COMMENT ON COLUMN VNDR_MAST.TRAD_END_DATE IS '거개종료일';
COMMENT ON COLUMN VNDR_MAST.COMP_TYPE IS '회사유형';
COMMENT ON COLUMN VNDR_MAST.COMP_CHAR IS '업체특성(가공/기능/고무/..)';
COMMENT ON COLUMN VNDR_MAST.COMP_IND IS '업종';
COMMENT ON COLUMN VNDR_MAST.MAIN_PROD_ITEM IS '주생산품목';
COMMENT ON COLUMN VNDR_MAST.MAIN_TRAD_ITEM IS '당사 주거래품목';
COMMENT ON COLUMN VNDR_MAST.COMP_EST_DATE IS '설립일';
COMMENT ON COLUMN VNDR_MAST.ADMN_PERS IS '관리직(명)';
COMMENT ON COLUMN VNDR_MAST.LABR_PERS IS '기능직(명)';
COMMENT ON COLUMN VNDR_MAST.TOT_EMPL IS '총 종업원수(정규직)';
COMMENT ON COLUMN VNDR_MAST.COMP_ADDR IS '본사-주소';
COMMENT ON COLUMN VNDR_MAST.COMP_LAND IS '본사-대지(평)';
COMMENT ON COLUMN VNDR_MAST.COMP_BULD IS '본사-건평';
COMMENT ON COLUMN VNDR_MAST.COMP_OWNR IS '본사-소유권';
COMMENT ON COLUMN VNDR_MAST.COMP_TEL IS '본사-전화번호';
COMMENT ON COLUMN VNDR_MAST.PLNT_ADDR IS '공장-주소';
COMMENT ON COLUMN VNDR_MAST.PLNT_LAND IS '공장-대지(평)';
COMMENT ON COLUMN VNDR_MAST.PLNT_BULD IS '공장-건평';
COMMENT ON COLUMN VNDR_MAST.PLNT_OWNR IS '공장-소유권';
COMMENT ON COLUMN VNDR_MAST.PLNT_TEL IS '공장-전화번호';
COMMENT ON COLUMN VNDR_MAST.CEO_NAME IS '대표자-명';
COMMENT ON COLUMN VNDR_MAST.CEO_SNUM IS '대표자-주민번호';
COMMENT ON COLUMN VNDR_MAST.CEO_EDU IS '대표자-최종학력';
COMMENT ON COLUMN VNDR_MAST.CEO_TEL IS '대표자-휴대폰번호';
COMMENT ON COLUMN VNDR_MAST.COMP_MEMO IS '메모';
COMMENT ON COLUMN VNDR_MAST.REGI_ID IS '등록자';
COMMENT ON COLUMN VNDR_MAST.REGI_DATE IS '등록일자';
COMMENT ON COLUMN VNDR_MAST.CHNG_ID IS '수정자';
COMMENT ON COLUMN VNDR_MAST.CHNG_DATE IS '수정일자';

CREATE TABLE VNDR_HIST
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  VNDR_CODE  VARCHAR2(20 BYTE)                  NOT NULL,
  HIST_SEQ   NUMBER(5)                          NOT NULL,
  HIST_MEMO  VARCHAR2(256 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, VNDR_CODE, HIST_SEQ)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE VNDR_HIST IS 'Vendor - 이력';
COMMENT ON COLUMN VNDR_HIST.SYS_ID IS '시스템ID';
COMMENT ON COLUMN VNDR_HIST.VNDR_CODE IS '업체코드';
COMMENT ON COLUMN VNDR_HIST.HIST_SEQ IS '순서';
COMMENT ON COLUMN VNDR_HIST.HIST_MEMO IS '메모';
COMMENT ON COLUMN VNDR_HIST.REGI_ID IS '등록자';
COMMENT ON COLUMN VNDR_HIST.REGI_DATE IS '등록일자';
COMMENT ON COLUMN VNDR_HIST.CHNG_ID IS '수정자';
COMMENT ON COLUMN VNDR_HIST.CHNG_DATE IS '수정일자';

CREATE TABLE VNDR_EMPL
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  VNDR_CODE  VARCHAR2(20 BYTE)                  NOT NULL,
  EMPL_SEQ   NUMBER(5)                          NOT NULL,
  EMPL_NAME  VARCHAR2(64 BYTE),
  EMPL_POSI  VARCHAR2(32 BYTE),
  EMPL_DEPT  VARCHAR2(64 BYTE),
  EMPL_ROLE  VARCHAR2(32 BYTE),
  EMPL_TEL   VARCHAR2(20 BYTE),
  EMPL_HP    VARCHAR2(20 BYTE),
  EMPL_FAX   VARCHAR2(20 BYTE),
  EMPL_MAIL  VARCHAR2(64 BYTE),
  EMPL_MEMO  VARCHAR2(256 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, VNDR_CODE, EMPL_SEQ)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE VNDR_EMPL IS 'Vendor - 직원정보';
COMMENT ON COLUMN VNDR_EMPL.SYS_ID IS '시스템ID';
COMMENT ON COLUMN VNDR_EMPL.VNDR_CODE IS '업체코드';
COMMENT ON COLUMN VNDR_EMPL.EMPL_SEQ IS '순서';
COMMENT ON COLUMN VNDR_EMPL.EMPL_NAME IS '성명';
COMMENT ON COLUMN VNDR_EMPL.EMPL_POSI IS '직급';
COMMENT ON COLUMN VNDR_EMPL.EMPL_DEPT IS '부서';
COMMENT ON COLUMN VNDR_EMPL.EMPL_ROLE IS '담당업무';
COMMENT ON COLUMN VNDR_EMPL.EMPL_TEL IS '전화';
COMMENT ON COLUMN VNDR_EMPL.EMPL_HP IS '핸드폰';
COMMENT ON COLUMN VNDR_EMPL.EMPL_FAX IS '팩스';
COMMENT ON COLUMN VNDR_EMPL.EMPL_MAIL IS '이메일';
COMMENT ON COLUMN VNDR_EMPL.EMPL_MEMO IS '메모';
COMMENT ON COLUMN VNDR_EMPL.REGI_ID IS '등록자';
COMMENT ON COLUMN VNDR_EMPL.REGI_DATE IS '등록일자';
COMMENT ON COLUMN VNDR_EMPL.CHNG_ID IS '수정자';
COMMENT ON COLUMN VNDR_EMPL.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_JOB_MAST
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  JOB_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  JOB_TYPE   VARCHAR2(20 BYTE),
  JOB_TIME   VARCHAR2(20 BYTE),
  JOB_DESC   VARCHAR2(512 BYTE),
  USE_FLAG   CHAR(1 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, JOB_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_JOB_MAST IS '(배치)작업관리';
COMMENT ON COLUMN SYS_JOB_MAST.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_JOB_MAST.JOB_ID IS '작업ID';
COMMENT ON COLUMN SYS_JOB_MAST.JOB_TYPE IS '작업구분';
COMMENT ON COLUMN SYS_JOB_MAST.JOB_TIME IS '작업시간';
COMMENT ON COLUMN SYS_JOB_MAST.JOB_DESC IS '작업설명';
COMMENT ON COLUMN SYS_JOB_MAST.USE_FLAG IS '사용여부';
COMMENT ON COLUMN SYS_JOB_MAST.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_JOB_MAST.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_JOB_MAST.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_JOB_MAST.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_JOB_LOGS
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  JOB_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  BGN_DATE   VARCHAR2(20 BYTE)                  NOT NULL,
  JOB_SEQ    NUMBER(7)                          NOT NULL,
  JOB_FILE   VARCHAR2(100 BYTE),
  JOB_CONT   VARCHAR2(1024 BYTE),
  JOB_RSLT   VARCHAR2(20 BYTE),
  RSLT_DESC  VARCHAR2(256 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, JOB_ID, BGN_DATE, JOB_SEQ)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_JOB_LOGS IS '(배치)작업 이력/로그관리';
COMMENT ON COLUMN SYS_JOB_LOGS.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_JOB_LOGS.JOB_ID IS '작업ID';
COMMENT ON COLUMN SYS_JOB_LOGS.BGN_DATE IS '시작일시';
COMMENT ON COLUMN SYS_JOB_LOGS.JOB_SEQ IS '작업SEQ.';
COMMENT ON COLUMN SYS_JOB_LOGS.JOB_FILE IS '작업파일';
COMMENT ON COLUMN SYS_JOB_LOGS.JOB_CONT IS '작업내용';
COMMENT ON COLUMN SYS_JOB_LOGS.JOB_RSLT IS '작업결과';
COMMENT ON COLUMN SYS_JOB_LOGS.RSLT_DESC IS '결과설명';
COMMENT ON COLUMN SYS_JOB_LOGS.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_JOB_LOGS.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_JOB_LOGS.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_JOB_LOGS.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_JOB_HIST
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  JOB_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  BGN_DATE   VARCHAR2(20 BYTE)                  NOT NULL,
  FILE_SEQ   NUMBER(7)                          NOT NULL,
  END_DATE   VARCHAR2(20 BYTE),
  JOB_FILE   VARCHAR2(100 BYTE),
  JOB_RSLT   VARCHAR2(20 BYTE),
  RSLT_DESC  VARCHAR2(256 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, JOB_ID, BGN_DATE, FILE_SEQ)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_JOB_HIST IS '(배치)작업 이력관리';
COMMENT ON COLUMN SYS_JOB_HIST.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_JOB_HIST.JOB_ID IS '작업ID';
COMMENT ON COLUMN SYS_JOB_HIST.BGN_DATE IS '시작일시';
COMMENT ON COLUMN SYS_JOB_HIST.FILE_SEQ IS '파일SEQ.';
COMMENT ON COLUMN SYS_JOB_HIST.END_DATE IS '종료일시';
COMMENT ON COLUMN SYS_JOB_HIST.JOB_FILE IS '작업파일';
COMMENT ON COLUMN SYS_JOB_HIST.JOB_RSLT IS '작업결과';
COMMENT ON COLUMN SYS_JOB_HIST.RSLT_DESC IS '결과설명';
COMMENT ON COLUMN SYS_JOB_HIST.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_JOB_HIST.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_JOB_HIST.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_JOB_HIST.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_HELP
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  USER_ID    VARCHAR2(20 BYTE)                  NOT NULL,
  PROG_ID    VARCHAR2(128 BYTE)                 NOT NULL,
  PROG_HELP  VARCHAR2(4000 BYTE),
  HELP_LOC   VARCHAR2(128 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, USER_ID, PROG_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_HELP IS '도움말 정보';
COMMENT ON COLUMN SYS_HELP.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_HELP.USER_ID IS '사용자 ID';
COMMENT ON COLUMN SYS_HELP.PROG_ID IS '화면ID';
COMMENT ON COLUMN SYS_HELP.PROG_HELP IS '도움말';
COMMENT ON COLUMN SYS_HELP.HELP_LOC IS '도움말상세 위치(ID)';
COMMENT ON COLUMN SYS_HELP.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_HELP.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_HELP.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_HELP.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_DIC
(
  SYS_ID       VARCHAR2(20 BYTE)                NOT NULL,
  ITEM_GRP     VARCHAR2(20 BYTE)                NOT NULL,
  ITEM_ID      VARCHAR2(20 BYTE)                NOT NULL,
  ITEM_NM      VARCHAR2(64 BYTE),
  ITEM_NM_KOR  VARCHAR2(64 BYTE),
  ITEM_NM_ENG  VARCHAR2(64 BYTE),
  ITEM_DESC    VARCHAR2(256 BYTE),
  ITEM_TYPE    VARCHAR2(10 BYTE),
  ITEM_LEN     NUMBER(12,3)                     DEFAULT 0                     NOT NULL,
  ITEM_SCALE   NUMBER(12,3)                     DEFAULT 0                     NOT NULL,
  ITEM_ATR1    VARCHAR2(20 BYTE),
  ITEM_ATR2    VARCHAR2(20 BYTE),
  ITEM_ATR3    VARCHAR2(20 BYTE),
  ITEM_REMK    VARCHAR2(4000 BYTE),
  USE_FLAG     VARCHAR2(1 BYTE),
  REGI_ID      VARCHAR2(20 BYTE),
  REGI_DATE    DATE,
  CHNG_ID      VARCHAR2(20 BYTE),
  CHNG_DATE    DATE,
  PRIMARY KEY
 (SYS_ID, ITEM_GRP, ITEM_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_DIC IS '용어사전';
COMMENT ON COLUMN SYS_DIC.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_DIC.ITEM_GRP IS '사전 종류';
COMMENT ON COLUMN SYS_DIC.ITEM_ID IS '용어 ID';
COMMENT ON COLUMN SYS_DIC.ITEM_NM IS '용어 이름';
COMMENT ON COLUMN SYS_DIC.ITEM_NM_KOR IS '용어 표시(한글)';
COMMENT ON COLUMN SYS_DIC.ITEM_NM_ENG IS '용어 표시(영문)';
COMMENT ON COLUMN SYS_DIC.ITEM_DESC IS '용어 설명';
COMMENT ON COLUMN SYS_DIC.ITEM_TYPE IS '용어 TYPE';
COMMENT ON COLUMN SYS_DIC.ITEM_LEN IS '용어 LENGTH';
COMMENT ON COLUMN SYS_DIC.ITEM_SCALE IS '용어 SCALE';
COMMENT ON COLUMN SYS_DIC.ITEM_ATR1 IS '용어 속성1';
COMMENT ON COLUMN SYS_DIC.ITEM_ATR2 IS '용어 속성2';
COMMENT ON COLUMN SYS_DIC.ITEM_ATR3 IS '용어 속성3';
COMMENT ON COLUMN SYS_DIC.ITEM_REMK IS '비고';
COMMENT ON COLUMN SYS_DIC.USE_FLAG IS '사용여부';
COMMENT ON COLUMN SYS_DIC.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_DIC.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_DIC.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_DIC.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_DATA_USER
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  USER_ID       VARCHAR2(20 BYTE)               NOT NULL,
  USER_NM       VARCHAR2(32 BYTE),
  USER_PW       VARCHAR2(256 BYTE),
  USER_LEVL     VARCHAR2(10 BYTE),
  USE_FLAG      VARCHAR2(1 BYTE),
  REGI_DATE     VARCHAR2(10 BYTE),
  REGI_USER_NO  VARCHAR2(10 BYTE),
  CHNG_DATE     VARCHAR2(10 BYTE),
  CHNG_USER_NO  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_USER
 PRIMARY KEY
 (SYS_ID, USER_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_DATA_UGRP
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  USER_ID       VARCHAR2(20 BYTE)               NOT NULL,
  GRUP_ID       VARCHAR2(20 BYTE)               NOT NULL,
  USE_FLAG      VARCHAR2(1 BYTE),
  REGI_DATE     VARCHAR2(10 BYTE),
  REGI_USER_NO  VARCHAR2(10 BYTE),
  CHNG_DATE     VARCHAR2(10 BYTE),
  CHNG_USER_NO  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_UGRP
 PRIMARY KEY
 (SYS_ID, USER_ID, GRUP_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_DATA_UAUT
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  USER_ID       VARCHAR2(20 BYTE)               NOT NULL,
  AUTH_ID       VARCHAR2(100 BYTE)              NOT NULL,
  AUTH_TYPE     VARCHAR2(20 BYTE),
  USE_FLAG      VARCHAR2(1 BYTE),
  REGI_DATE     VARCHAR2(10 BYTE),
  REGI_USER_NO  VARCHAR2(10 BYTE),
  CHNG_DATE     VARCHAR2(10 BYTE),
  CHNG_USER_NO  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_UAUT
 PRIMARY KEY
 (SYS_ID, USER_ID, AUTH_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_DATA_TBLM
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  TBL_ID        VARCHAR2(20 BYTE)               NOT NULL,
  COL_SEQ       NUMBER(5),
  COL_ID        VARCHAR2(20 BYTE)               NOT NULL,
  COL_NM        VARCHAR2(64 BYTE),
  COL_TYPE      VARCHAR2(10 BYTE),
  COL_LEN       NUMBER(12,3),
  COL_SCALE     NUMBER(12,3),
  COL_NULL      VARCHAR2(1 BYTE),
  COL_PK        NUMBER(2),
  COL_IDX1      NUMBER(2),
  COL_IDX2      NUMBER(2),
  COL_IDX3      NUMBER(2),
  COL_NACD      VARCHAR2(10 BYTE),
  COL_INIT      VARCHAR2(64 BYTE),
  COL_REMK      VARCHAR2(256 BYTE),
  USE_FLAG      VARCHAR2(1 BYTE),
  REGI_DATE     VARCHAR2(10 BYTE),
  REGI_USER_NO  VARCHAR2(10 BYTE),
  CHNG_DATE     VARCHAR2(10 BYTE),
  CHNG_USER_NO  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_TBLM
 PRIMARY KEY
 (SYS_ID, TBL_ID, COL_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_DATA_JOBS
(
  JOB_NO        VARCHAR2(20 BYTE)               NOT NULL,
  ARG_CD        VARCHAR2(32 BYTE)               NOT NULL,
  ARG_NAME      VARCHAR2(32 BYTE),
  ARG_SEQ       NUMBER(15,3),
  ARG_TYPE      VARCHAR2(10 BYTE),
  ARG_LEN       NUMBER(15,3),
  ARG_DESC      VARCHAR2(64 BYTE),
  ARG_VALU      VARCHAR2(64 BYTE),
  USE_FLAG      VARCHAR2(1 BYTE),
  REGI_DATE     VARCHAR2(10 BYTE),
  REGI_USER_NO  VARCHAR2(10 BYTE),
  CHNG_DATE     VARCHAR2(10 BYTE),
  CHNG_USER_NO  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_JOBS
 PRIMARY KEY
 (JOB_NO, ARG_CD)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_DATA_JOBM
(
  JOB_NO        VARCHAR2(20 BYTE)               NOT NULL,
  JOB_TYPE      VARCHAR2(10 BYTE),
  JOB_LEVL      VARCHAR2(10 BYTE),
  JOB_NAME      VARCHAR2(100 BYTE),
  JOB_DESC      VARCHAR2(100 BYTE),
  JOB_SQL1      VARCHAR2(4000 BYTE),
  JOB_SQL2      VARCHAR2(4000 BYTE),
  JOB_SQL3      VARCHAR2(4000 BYTE),
  JOB_SQL4      VARCHAR2(4000 BYTE),
  JOB_SQL5      VARCHAR2(4000 BYTE),
  USE_FLAG      VARCHAR2(1 BYTE),
  REGI_DATE     VARCHAR2(10 BYTE),
  REGI_USER_NO  VARCHAR2(10 BYTE),
  CHNG_DATE     VARCHAR2(10 BYTE),
  CHNG_USER_NO  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_JOBM
 PRIMARY KEY
 (JOB_NO)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_DATA_GRUP
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  GRUP_ID       VARCHAR2(20 BYTE)               NOT NULL,
  GRUP_NM       VARCHAR2(32 BYTE),
  GRUP_DESC     VARCHAR2(256 BYTE),
  USE_FLAG      VARCHAR2(1 BYTE),
  REGI_DATE     VARCHAR2(10 BYTE),
  REGI_USER_NO  VARCHAR2(10 BYTE),
  CHNG_DATE     VARCHAR2(10 BYTE),
  CHNG_USER_NO  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_GRUP
 PRIMARY KEY
 (SYS_ID, GRUP_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_DATA_GAUT
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  GRUP_ID       VARCHAR2(20 BYTE)               NOT NULL,
  AUTH_ID       VARCHAR2(100 BYTE)              NOT NULL,
  AUTH_TYPE     VARCHAR2(20 BYTE),
  USE_FLAG      VARCHAR2(1 BYTE),
  REGI_DATE     VARCHAR2(10 BYTE),
  REGI_USER_NO  VARCHAR2(10 BYTE),
  CHNG_DATE     VARCHAR2(10 BYTE),
  CHNG_USER_NO  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_GAUT
 PRIMARY KEY
 (SYS_ID, GRUP_ID, AUTH_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_DATA_DIC
(
  SYS_ID        VARCHAR2(20 BYTE)               NOT NULL,
  ITEM_GRP      VARCHAR2(20 BYTE)               NOT NULL,
  ITEM_ID       VARCHAR2(20 BYTE)               NOT NULL,
  ITEM_NM       VARCHAR2(64 BYTE),
  ITEM_NM_ENG   VARCHAR2(64 BYTE),
  ITEM_DESC     VARCHAR2(256 BYTE),
  ITEM_TYPE     VARCHAR2(10 BYTE),
  ITEM_LEN      NUMBER(12,3),
  ITEM_SCALE    NUMBER(12,3),
  ITEM_ATR1     VARCHAR2(20 BYTE),
  ITEM_ATR2     VARCHAR2(20 BYTE),
  ITEM_ATR3     VARCHAR2(20 BYTE),
  ITEM_REMK     VARCHAR2(4000 BYTE),
  USE_FLAG      VARCHAR2(1 BYTE),
  REGI_DATE     VARCHAR2(10 BYTE),
  REGI_USER_NO  VARCHAR2(10 BYTE),
  CHNG_DATE     VARCHAR2(10 BYTE),
  CHNG_USER_NO  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_DIC
 PRIMARY KEY
 (SYS_ID, ITEM_GRP, ITEM_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_DATA_CODE
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_GRP   VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_ID    VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_NAME  VARCHAR2(64 BYTE),
  CODE_DESC  VARCHAR2(256 BYTE),
  CODE_TYPE  VARCHAR2(20 BYTE),
  CODE_SEQ   NUMBER(12,3),
  CODE_CHR1  VARCHAR2(20 BYTE),
  CODE_CHR2  VARCHAR2(20 BYTE),
  CODE_CHR3  VARCHAR2(20 BYTE),
  CODE_CHR4  VARCHAR2(20 BYTE),
  CODE_CHR5  VARCHAR2(20 BYTE),
  CODE_CHR6  VARCHAR2(20 BYTE),
  CODE_CHR7  VARCHAR2(20 BYTE),
  CODE_NUM1  NUMBER(12,3),
  CODE_NUM2  NUMBER(12,3),
  CODE_NUM3  NUMBER(12,3),
  USE_FLAG   VARCHAR2(1 BYTE),
  REGI_DATE  VARCHAR2(10 BYTE),
  REGI_USER  VARCHAR2(10 BYTE),
  CHNG_DATE  VARCHAR2(10 BYTE),
  CHNG_USER  VARCHAR2(10 BYTE),
  CONSTRAINT PK_SYS_DATA_CODE
 PRIMARY KEY
 (SYS_ID, CODE_GRP, CODE_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SYS_COM_MEM
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  COMM_ID    VARCHAR2(20 BYTE)                  NOT NULL,
  MEMB_ID    VARCHAR2(20 BYTE)                  NOT NULL,
  MEMB_LVL   VARCHAR2(20 BYTE),
  IN_DATE    VARCHAR2(10 BYTE),
  OUT_DATE   VARCHAR2(10 BYTE),
  ACT_IDX    VARCHAR2(20 BYTE),
  COMM_REMK  VARCHAR2(256 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, COMM_ID, MEMB_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_COM_MEM IS '커뮤니티 멤버관리';
COMMENT ON COLUMN SYS_COM_MEM.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_COM_MEM.COMM_ID IS 'Community ID';
COMMENT ON COLUMN SYS_COM_MEM.MEMB_ID IS 'Member ID';
COMMENT ON COLUMN SYS_COM_MEM.MEMB_LVL IS 'Member 등급/역할';
COMMENT ON COLUMN SYS_COM_MEM.IN_DATE IS '가입일';
COMMENT ON COLUMN SYS_COM_MEM.OUT_DATE IS '탈퇴일';
COMMENT ON COLUMN SYS_COM_MEM.ACT_IDX IS '활동여부';
COMMENT ON COLUMN SYS_COM_MEM.COMM_REMK IS '비고';
COMMENT ON COLUMN SYS_COM_MEM.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_COM_MEM.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_COM_MEM.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_COM_MEM.CHNG_DATE IS '수정일자';

CREATE TABLE SYS_CODE_TERM
(
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_GRUP  VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_DATE  VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_CD    VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_NAME  VARCHAR2(128 BYTE),
  CODE_DESC  VARCHAR2(256 BYTE),
  SORT_SEQ   NUMBER(5)                          DEFAULT 0                     NOT NULL,
  USE_FLAG   CHAR(1 BYTE),
  EXT_CHR01  VARCHAR2(128 BYTE),
  EXT_CHR02  VARCHAR2(128 BYTE),
  EXT_CHR03  VARCHAR2(128 BYTE),
  EXT_CHR04  VARCHAR2(128 BYTE),
  EXT_CHR05  VARCHAR2(128 BYTE),
  EXT_CHR06  VARCHAR2(128 BYTE),
  EXT_CHR07  VARCHAR2(128 BYTE),
  EXT_CHR08  VARCHAR2(128 BYTE),
  EXT_CHR09  VARCHAR2(128 BYTE),
  EXT_CHR10  VARCHAR2(128 BYTE),
  EXT_NUM01  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM02  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM03  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM04  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM05  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_TEXT   VARCHAR2(512 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (SYS_ID, CODE_GRUP, CODE_DATE, CODE_CD)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_CODE_TERM IS '코드관리(BP)';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR10 IS '문자속성10';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_NUM01 IS '숫자속성01';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_NUM02 IS '숫자속성02';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_NUM03 IS '숫자속성03';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_NUM04 IS '숫자속성04';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_NUM05 IS '숫자속성05';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_TEXT IS '기타정보';
COMMENT ON COLUMN SYS_CODE_TERM.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_CODE_TERM.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_CODE_TERM.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_CODE_TERM.CHNG_DATE IS '수정일자';
COMMENT ON COLUMN SYS_CODE_TERM.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_CODE_TERM.CODE_GRUP IS '코드그룹';
COMMENT ON COLUMN SYS_CODE_TERM.CODE_DATE IS '적용일자';
COMMENT ON COLUMN SYS_CODE_TERM.CODE_CD IS '코드';
COMMENT ON COLUMN SYS_CODE_TERM.CODE_NAME IS '코드명칭';
COMMENT ON COLUMN SYS_CODE_TERM.CODE_DESC IS '코드설명';
COMMENT ON COLUMN SYS_CODE_TERM.SORT_SEQ IS '순서';
COMMENT ON COLUMN SYS_CODE_TERM.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR01 IS '문자속성01';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR02 IS '문자속성02';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR03 IS '문자속성03';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR04 IS '문자속성04';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR05 IS '문자속성05';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR06 IS '문자속성06';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR07 IS '문자속성07';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR08 IS '문자속성08';
COMMENT ON COLUMN SYS_CODE_TERM.EXT_CHR09 IS '문자속성09';

CREATE TABLE SYS_CODE_HIST
(
  HIST_DATE  DATE                               NOT NULL,
  HIST_TYPE  VARCHAR2(20 BYTE)                  NOT NULL,
  SYS_ID     VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_GRUP  VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_CD    VARCHAR2(20 BYTE)                  NOT NULL,
  CODE_NAME  VARCHAR2(128 BYTE),
  CODE_DESC  VARCHAR2(256 BYTE),
  SORT_SEQ   NUMBER(5)                          DEFAULT 0                     NOT NULL,
  USE_FLAG   CHAR(1 BYTE),
  EXT_CHR01  VARCHAR2(128 BYTE),
  EXT_CHR02  VARCHAR2(128 BYTE),
  EXT_CHR03  VARCHAR2(128 BYTE),
  EXT_CHR04  VARCHAR2(128 BYTE),
  EXT_CHR05  VARCHAR2(128 BYTE),
  EXT_CHR06  VARCHAR2(128 BYTE),
  EXT_CHR07  VARCHAR2(128 BYTE),
  EXT_CHR08  VARCHAR2(128 BYTE),
  EXT_CHR09  VARCHAR2(128 BYTE),
  EXT_CHR10  VARCHAR2(128 BYTE),
  EXT_NUM01  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM02  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM03  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM04  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_NUM05  NUMBER(15,3)                       DEFAULT 0                     NOT NULL,
  EXT_TEXT   VARCHAR2(512 BYTE),
  REGI_ID    VARCHAR2(20 BYTE),
  REGI_DATE  DATE,
  CHNG_ID    VARCHAR2(20 BYTE),
  CHNG_DATE  DATE,
  PRIMARY KEY
 (HIST_DATE, HIST_TYPE, SYS_ID, CODE_GRUP, CODE_CD)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
COMMENT ON TABLE SYS_CODE_HIST IS '코드관리(변경이력)';
COMMENT ON COLUMN SYS_CODE_HIST.HIST_DATE IS '변경 HISTORY 일자';
COMMENT ON COLUMN SYS_CODE_HIST.HIST_TYPE IS '변경 HISTORY 구분';
COMMENT ON COLUMN SYS_CODE_HIST.SYS_ID IS '시스템ID';
COMMENT ON COLUMN SYS_CODE_HIST.CODE_GRUP IS '코드그룹';
COMMENT ON COLUMN SYS_CODE_HIST.CODE_CD IS '코드';
COMMENT ON COLUMN SYS_CODE_HIST.CODE_NAME IS '코드명칭';
COMMENT ON COLUMN SYS_CODE_HIST.CODE_DESC IS '코드설명';
COMMENT ON COLUMN SYS_CODE_HIST.SORT_SEQ IS '순서';
COMMENT ON COLUMN SYS_CODE_HIST.USE_FLAG IS '사용유무';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR01 IS '문자속성01';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR02 IS '문자속성02';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR03 IS '문자속성03';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR04 IS '문자속성04';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR05 IS '문자속성05';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR06 IS '문자속성06';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR07 IS '문자속성07';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR08 IS '문자속성08';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR09 IS '문자속성09';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_CHR10 IS '문자속성10';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_NUM01 IS '숫자속성01';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_NUM02 IS '숫자속성02';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_NUM03 IS '숫자속성03';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_NUM04 IS '숫자속성04';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_NUM05 IS '숫자속성05';
COMMENT ON COLUMN SYS_CODE_HIST.EXT_TEXT IS '기타정보';
COMMENT ON COLUMN SYS_CODE_HIST.REGI_ID IS '등록자';
COMMENT ON COLUMN SYS_CODE_HIST.REGI_DATE IS '등록일자';
COMMENT ON COLUMN SYS_CODE_HIST.CHNG_ID IS '수정자';
COMMENT ON COLUMN SYS_CODE_HIST.CHNG_DATE IS '수정일자';

